### ISSUE TITLE
Las fechas no aparecen traducidas en el programa

### ISSUE THREAD

**Issue by sukiletxe** [manuelcortez/TWBlue#1]
El programa utiliza los valores españoles de los días de la semana y los meses al construir las fechas, ignorando las que aparecen el el archivo de localización. Testeado con español, inglés, euskera y ruso.

**Comment by codeofdusk** [comment]
Buenos dias. Por consistencia, por favor escriba su notas en inglés. No hablo español bien, y la idioma de esta programa es inglés. Puedo hablar español en twitter, http://twitter.com/codeofdusk. @manuelcortez es mexicano, él habla español. @manuelcortez Por favor arregla este. Gracias.

**Comment by sukiletxe** [comment]
Hello,
This issue is not relevant anymore, since now only the numeric value is used in all dates by default, and by the way, I don't know how to change this behaviour per language nor if it can be changed. I'm closing this issue.
