### ISSUE TITLE
Improvements in the image detection algorithm and OCR

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#105]
Sometimes the detection image algorithm gives a positive but the OCR can't get the image to scan. It is due to the image OCR algorithm taking the normal tweet and the image detection taking images from retweets too.

**Comment by Mohamed00** [comment]
Speaking of that, OCR has a bug which causes images not to be 
detected in quoted tweets.

 ----- Original Message -----

**Comment by manuelcortez** [comment]
Unfortunately I can't make quoted tweets to work the same, because basically I have to get two tweets, and merge their text field. After merged, I remove the "original" tweet and its metadata.
