### ISSUE TITLE
Remove API key from sndup

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#109]
As Sndup seems no longer supports API keys for uploading audio, I think we should drop that support for now, until it will be added to the service.

**Comment by Mohamed00** [comment]
Yes, I've noticed that I can't find an API key anywhere, even 
though I have an account.  Is Snd Up aware of this?

 ----- Original Message -----

**Comment by manuelcortez** [comment]
No idea, really. He has been changing the service lots of times.

**Comment by Mohamed00** [comment]
We're lucky the API still works Xd.

 ----- Original Message -----
