### ISSUE TITLE
TW Blue sometimes doesn't show The Newest Tweets in user's Timeline

### ISSUE THREAD

**Issue by abdulrahmanessam** [manuelcortez/TWBlue#116]
When I View My Followers' Timeline it shows Tweets which it's 3 Days ago

Sometimes it doesn't happened

**Comment by manuelcortez** [comment]
are you using it from source?

**Comment by abdulrahmanessam** [comment]
No

I use The latest version

**Comment by abdulrahmanessam** [comment]
This ishu happened when I change max API calls

**Comment by Mohamed00** [comment]
Hmm, that may or may not have something to do with it. According to @manuelcortez, The API calls options is an 
option you really shouldn't touch, as setting it two high could result 
in you being rate limited. In fact, the documentation on that option 
could use some improvement. However, I believe this probably does not have anything to do with your issue. The bug where old tweets appear as the most recent in a timeline is a long standing one.
