### ISSUE TITLE
Mention and dm buttons do notwork

### ISSUE THREAD

**Issue by burakyuksek** [manuelcortez/TWBlue#127]
When focused on friends or followers buffers, clicking on buttons like mention or dm does nothing, and their strings seem untranslated as well.

**Comment by manuelcortez** [comment]
Are you sure it's not a translation issue? I can see these buttons perfectly in my language (Spanish) and they are showing their corresponding dialogs.

**Comment by burakyuksek** [comment]
Hello,
The buttons show up and work correctly in the home buffer, not in the friends or followers buffers. I don't know what is wrong, since the buttons show up and work correctly in home bufer, I don2t think it's a translation issue.

**Comment by manuelcortez** [comment]
Can you switch to english and try to reproduce the same problem? If it still doesn't work, can you post your logs here?

**Comment by burakyuksek** [comment]
I have discovered that the dm button works, but the mention button does not. That means I have a translation problem. I am sorry. The logs are attached. 




[debug.txt](https://github.com/manuelcortez/TWBlue/files/886804/debug.txt)
[error.txt](https://github.com/manuelcortez/TWBlue/files/886805/error.txt)

**Comment by burakyuksek** [comment]
I have fixed the issues. I am very sorry about the trouble I have caused.

**Comment by manuelcortez** [comment]
No problem :) I will close the issue now, and this will be fixed very soon, as I will release a new version in a few days.
