### ISSUE TITLE
Audio Uploader Retaining Files After they are Uploaded

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#130]
I've noticed that whenever a file is uploaded using the audio uploader, it can't be deleted. For some reason, the file is still being used by TW Blue, requiring a client restart to fix. This also effects recording files. tW Blue is unable to delete them after they are uploaded because of this problem.

**Comment by codeofdusk** [comment]
My first guess for why this is happening is a file handle left open. Will look at the code to confirm.

Bill
