### ISSUE TITLE
TWBlue shows old objects like if they were new

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#133]
Sometimes TWBlue is receibing older objects from the Twitter API and it puts them in place of newer elements. It has been discussed previously in #116. I think we should limit somehow (maybe by using creation date of the oldest item in the buffer?) new item addition in buffers when we got them.

**Comment by jmdaweb** [comment]
I would use extra variables to keep the date of the newest object when the buffers are updated. If an object arrives and its date is older than the kept date, we can ignore it. But it can cause problems if an object arrives in a manual update, but not when the stream was updated. To workaround this, I would perform a second check aplying a limit (if the new object is older than 1 day, for example). These two checks could be the solution.
