### ISSUE TITLE
Settings: port new buffer interface to GTK

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#14]
The new buffers interface hasn't been ported to GTK yet. The dialog is blank.

**Comment by manuelcortez** [comment]
I think I'll going to finish most of the GTK interface after the first new generation release in windows. It will be included in the GTK dialogs.

**Comment by codeofdusk** [comment]
Alright.

Don’t close the issue though, keep it open until you do it.

Bill
