### ISSUE TITLE
Reply does not show who is being replied to.

### ISSUE THREAD

**Issue by kylecunningham** [manuelcortez/TWBlue#143]
So this is something I've been meaning to bring up for a while. The reply (ctrl+win+r on most windows platforms) does not show the user(s) being replied to. This can be an issue, especially when attempting to reply to multiple conversations at once.
Is there any way this can be fixed?

**Comment by codeofdusk** [comment]
This issue will close once:

* #144 is merged into the py3 branch
* py3 is merged into the next-gen (main) branch
