### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#15]
Right now, an experimental persistence system has been implemented.
We should have some way of making sure the database doesn't become too large, clearing out old records, etc.
It should be enabled by default when made manageable, as it is useful. But users should be able to disable it, as some don't like it.

**Comment by codeofdusk** [comment]
@manuelcortez how should we determine when to purge the database? File size, time to load, or something else?

**Comment by manuelcortez** [comment]
I think we could use the file size. Why this should be enabled by default? It is a new feature and I don't think it should be enabled by default, because this project has been developed without a database in its "core features". So why enable a non-core feature by default?

**Comment by codeofdusk** [comment]
Because most users will probably want it, those who don’t are advanced users.

I will write a test for the database module, to see how long it takes it to load modules of various sizes to find an acceptable method of keeping the database at a manageable size.

Bill

**Comment by jmdaweb** [comment]
We should ask directly to the users about that. For example, we could make a google form.
Regards.

**Comment by manuelcortez** [comment]
@codeofdusk Could you create the google form?

**Comment by codeofdusk** [comment]
Yes I could, but it will be English only. My Spanish isn’t the greatest so you’ll need to create one for that.

I’ll also share my test results of playing with the database testing modules.

Bill

**Comment by codeofdusk** [comment]
I've written some constraints for database size. It only allows up to 1764 items to be cached per buffer at any given time by default. The constraints can be disabled, as can the entire caching mechanism. Also, users can make the cache bigger or smaller if they'd like, and disabling the cache deletes any already existing cache from the machine. I think this should stay open, and the feature should be enabled by default for the next snapshot. We'll see what problems are reported by those who run the snapshots (more people run from snapshots than from source), and before release we can run a Google form about default behavior for the final release.

**Comment by codeofdusk** [comment]
If a lot of users report huge databases or slow loading times, we can modify the default limit or disable the feature by default altogether.
