### ISSUE TITLE
Buffer configuration: buffer order in GUI out of sync with buffer order in config

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#16]
The GUI always displays buffers in a fixed order, which may or may not reflect the order of the buffers in the config file. Buffers hidden by the user should be displayed at the bottom of the list, order of these buffers is not important.

**Comment by codeofdusk** [comment]
Fix by commit 6fc7bee74c253007d0e59d20237fbb0be99070d8.

**Comment by codeofdusk** [comment]
Not actually fixed.

**Comment by codeofdusk** [comment]
I attempted to fix the issue, but it's still there. @manuelcortez  Please look at this.

**Comment by manuelcortez** [comment]
I can't reproduce this issue. Buffers appear to be ordered properly in my session.
