### ISSUE TITLE
Issue with quoted tweets

### ISSUE THREAD

**Issue by burakyuksek** [manuelcortez/TWBlue#160]
When there is a tweet quoted, and the quoted tweet has another quoted tweet inside it, the quoted tweet inside will show as a URL.

**Comment by jmdaweb** [comment]
I have talked to @manuelcortez about this more than once. It seems that retrieving all quoted tweets consumes too much api requests, so the limit would be reached in a shorter time.

**Comment by Mohamed00** [comment]
Workaround: use your keymap's view Tweet shortcut to display the full quoted Tweet discussion.
