### ISSUE TITLE
Broken URL Expansion

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#164]
### Steps to reproduce.
1. Try to expand a URL, example: http://ift.tt/1T2FubP.
### Expected.
The expanded URL should be displayed.
### Actual.
"URL expanded" is announced, but an expanded URL is not returned.
Possibly do to the fix for #159?

**Comment by manuelcortez** [comment]
Was it working before? Supported shorteners are only available in the url_shortener/shorteners folder. None of them seems to support that example.

**Comment by jmdaweb** [comment]
URL expansion method doesn’t use shorteners, except for acorta.me. The URL is visited using requests, all redirections are followed, and the final URL is returned from the requests answer object. Before urllib was used, so there was no proxy support.
Regards.

**Comment by jmdaweb** [comment]
Please, test audio playing and URL expansion with the latest commit. If it works, this issue can be closed.

**Comment by Mohamed00** [comment]
Expansion works, but Dropbox broke again with that commit.

**Comment by Mohamed00** [comment]
Updated previous comment. URL expansion works again.

**Comment by jmdaweb** [comment]
Wow, so we can close this and reopen the Dropbox issue.
