### ISSUE TITLE
give  twblue the ability to do dns lookups  when we are connected to   a sox 5 proxy.

### ISSUE THREAD

**Issue by hamzalatif7** [manuelcortez/TWBlue#165]
Hi I have a suggestion to make and I think it would improove the security of twblue. Could we have a checkbox on the proxy  tab to do dns  name lookups remotely when connectedthrew  to a sox 5  proxy   if that box is ticked  when the request for the  twitter  ip address is sent the request will be done  threw the proxy side  instead  of doing it on the ISP side. It shouldbe be  added as a checkbox so users  have a choice  if they wish to do the dns lookup  remotely or threw there service provider.

**Comment by jmdaweb** [comment]
Hi,
You can now choose wether you want remote DNS or not in the proxy type combo box, so this issue is fixed.
Regards.
