### ISSUE TITLE
Deleted Tweets Remain in Buffers

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#166]
While this should have been fixed in 0.82, it is apparently still occurring.
### Steps to reproduce.
1. Post a Tweet.
2. Delete it.
### Expected.
The deleted Tweet should disappear from all buffers.
### Actual.
The Tweet remains in all buffers.

**Comment by manuelcortez** [comment]
Closing as can't be fixed without streaming features.
