### ISSUE TITLE
Status of Mention to All and Long Tweet Checkboxes Shouldn't be Remembered

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#170]
While the reasoning behind this is understandable, I believe remembering the status of these checkboxes causes problems. Specifically, people may send long tweets without knowing it because they forgot to uncheck long tweet at one point, or they may inadvertently remove everyone from a thread because they forgot to re check mention to all. I believe the ability to remember the status of these checkboxes should either be removed, or made configurable.

**Comment by manuelcortez** [comment]
I think we will remove this soon. It does not make sense for me to add a configurable option for a configurable option
