### ISSUE TITLE
No timeline is initially focused at startup if Home buffer is hidden

### ISSUE THREAD

**Issue by jscholes** [manuelcortez/TWBlue#171]
Reproduce:

1. With a single account, hide the Home buffer.
2. Restart TWBlue (which for some reason is necessary to hide a buffer).

Expected: TWBlue focuses an alternative buffer upon startup and I can begin navigating tweets as normal.

Actual: TWBlue reports, "No session is currently in focus. Focus a session with the next or previous session shortcut.".

**Comment by codeofdusk** [comment]
Which buffer should we focus instead? The first available one?
Why would someone want to hide the home buffer?

Bill

**Comment by jscholes** [comment]
> Which buffer should we focus instead? The first available one?

The one that was focused when the application was closed would be the most obvious choice and the best one for usability.

> Why would someone want to hide the home buffer?

Does this matter?  Regardless of my specific use case, if the application allows the Home buffer to be hidden, then doing so should not have unattended side effects.

**Comment by manuelcortez** [comment]
Based in the "common" use cases for a twitter client and in the fact that we use the home_timeline buffer as a reference for some methods, I think the most reasonable option is to prevent this buffer to be hidden. Otherwise we would have to redefine fix_wrong_buffer, get_best_buffer, get_first_buffer and other buffer searching options. Any thoughts?

**Comment by jscholes** [comment]
I think it's reasonable to expect that the majority of users won't wish to hide their home buffer, certainly.  On the other hand, speaking as a software developer I really don't like the idea that the home buffer is such a single point of failure.  In terms of good application architecture, hiding the home buffer should be a level of flexibility that can easily be catered for.

Therefore, in this situation I'd probably take a step back and ask myself how the code could be refactored to allow someone to turn the home buffer off, and to stop treating the home buffer as a particularly special entity when in reality it's just another timeline.  That way, you could also start focusing the last used buffer on startup, and prevent the situation where the global hotkey-based interface tries to return my focus to the home buffer every time I hide the TWBlue main window.

As the owner of the project, it eventually rests with you to determine what your priorities are.  Clean code and application flexibility, or special cases because of existing code dependencies.  Given that I created this ticket, my preference would be that I could disable the home buffer altogether.  I don't read it and don't really want it taking up unnecessary memory.  I only really use Twitter to keep up with news and to send direct messages.
