### ISSUE TITLE
TWBlue wont start

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#175]
Hello. I tried regular version and source one. Only error and debug logs generated. I suspect that its some kind of problem with my operating system language. Its Serbian latin, Serbia.

[logs.zip](https://github.com/manuelcortez/TWBlue/files/1453829/logs.zip)

**Comment by jmdaweb** [comment]
Hello.

It seems that you are running from source in these logs. Please, paste the output displayed in your console, it might help. Otherwise, attach the stderr.log and stdout.log files too.

Regards.


El 08/11/2017 a las 13:30, agasoft escribió:

Hello. I tried regular version and source one. Only error and debug logs generated. I suspect that its some kind of problem with my operating system language. Its Serbian latin, Serbia.

logs.zip<https://github.com/manuelcortez/TWBlue/files/1453829/logs.zip>

**Comment by agasoft** [comment]
I dont know where to find those files? I have no any message in console. Program just start for a second and disapeer

**Comment by jmdaweb** [comment]
Go to your %temp% folder and look for stderr.log there.

Regards.

El 09/11/2017 a las 1:44, agasoft escribió:

I dont know where to find those files? I have no any message in console. Program just start for a second and disapeer

**Comment by agasoft** [comment]
Files not present in temp directory.

**Comment by jmdaweb** [comment]
Ok. Can you explain us how do you launch TWBlue from console? Do you use the run dialog, or open a console window previously? We suppose you are running from source. Is it right?

Regards.


El 09/11/2017 a las 14:45, agasoft escribió:

Files not present in temp directory.

**Comment by agasoft** [comment]
Yes, I am running from source. Just starting file main.py, as
described on your site. But the same error is present when I runnning
full installation version.
TW Blue worked only when my system was in English language.
Now its in Serbian latin, and TW blue wonts to start.

2017-11-09 14:55 GMT+01:00, José Manuel <notifications@github.com>:

**Comment by jmdaweb** [comment]
Ok. Try the following and let's see if it works:


* Run main.py from the console. Navigate to TWBlue\src folder, and type the following command: python main.py. If a traceback is displayed, paste it here.

* If you run TWBlue from a binary version, stderr.log and stdout.log will be created into %temp% directory. Once TWBlue runs successfully they are removed, but if they still are present, they contain the problem. Attach them if that is the case.


Regards.


El 09/11/2017 a las 14:58, agasoft escribió:
Yes, I am running from source. Just starting file main.py, as
described on your site. But the same error is present when I runnning
full installation version.
TW Blue worked only when my system was in English language.
Now its in Serbian latin, and TW blue wonts to start.

2017-11-09 14:55 GMT+01:00, José Manuel <notifications@github.com><mailto:notifications@github.com>:

**Comment by agasoft** [comment]
Traceback (most recent call last):
  File "C:\Users\agaso\twblue\src\main.py", line 99, in <module>
    setup()
  File "C:\Users\agaso\twblue\src\main.py", line 64, in setup
    languageHandler.setLanguage(config.app["app-settings"]["language"])
  File "C:\Users\agaso\twblue\src\languageHandler.py", line 127, in
setLanguage
    localeName=locale.windows_locale[windowsLCID]
KeyError: 9242

2017-11-09 15:04 GMT+01:00, José Manuel <notifications@github.com>:

**Comment by codeofdusk** [comment]
And that would be the problem.
I’d add an exception for KeyError that defaults the language to English. Will do later if you guys can’t.

Bill

**Comment by manuelcortez** [comment]
If the language is already supported in Windows we must add the ISO639 code instead forcing it to english. Will research about this topic.

**Comment by manuelcortez** [comment]
@agasoft as you are running from source, can you run the Python interpreter and tell me what this code returns?

import locale
locale.getdefaultlocale()

**Comment by agasoft** [comment]
Sure.
Just tell me how to do that...


2017-11-09 15:52 GMT+01:00, Manuel Cortéz <notifications@github.com>:

**Comment by manuelcortez** [comment]
I did it already. Open the python interpreter and type these lines.

**Comment by agasoft** [comment]
('sr_RS', 'cp1250

2017-11-09 16:02 GMT+01:00, Manuel Cortéz <notifications@github.com>:

**Comment by jmdaweb** [comment]
Hi @agasoft.
Try the following. If it works, we will change the code accordingly.
Open src/languageHandler.py with a text editor. We like Notepad++ very much, so We recommend it.
Locate a line with the text 'import locale'. It is in the first lines of the file.
Below this line, write the following line and save the file:
locale.windows_locale[9242]='sr_RS'
After that, try running TWBlue. If it works, we can close this issue.

**Comment by agasoft** [comment]
Strange.
When I entered this line without apostrophy, and clicking main.py
nothing happen.
No logs, no tracebacks.
What could be wrong?



2017-11-09 16:55 GMT+01:00, José Manuel <notifications@github.com>:

**Comment by jmdaweb** [comment]
If TWBlue doesn't run, a traceback is displayed somewhere.
Please, don't run TWBlue by clicking main.py. The console window can be displayed for less than a second and the traceback can't be copied. Press windows+r, type cmd.exe and press enter.
After that, navigate to the src directory and run the command: python main.py
Regards.

**Comment by agasoft** [comment]
SUre.
I had tracebacks before, but after I paste this code you gave to me,
all disapeered.
No tracebacks, no new logs generated, but tw blue not working yet.
I pasted code below line import locale.


2017-11-09 18:12 GMT+01:00, José Manuel <notifications@github.com>:

**Comment by jmdaweb** [comment]
Let's repeat the process. Look for stdout.log and stderr.log in %temp%. Check debug.log and error.log for new messages.

Regards.

El 09/11/2017 a las 18:19, agasoft escribió:
SUre.
I had tracebacks before, but after I paste this code you gave to me,
all disapeered.
No tracebacks, no new logs generated, but tw blue not working yet.
I pasted code below line import locale.


2017-11-09 18:12 GMT+01:00, José Manuel <notifications@github.com><mailto:notifications@github.com>:

**Comment by agasoft** [comment]
Yes, this file is coming.
[stderr.log](https://github.com/manuelcortez/TWBlue/files/1458559/stderr.log)

**Comment by jmdaweb** [comment]
OK, you have to add a single quote at the end of the line.

locale.windows_locale[9242]='sr_RS'
When you fix that, we will be able to continue to the next error, if any.
Regards.

El 09/11/2017 a las 18:28, agasoft escribió:

Yes, this file is coming.
stderr.log<https://github.com/manuelcortez/TWBlue/files/1458559/stderr.log>

**Comment by agasoft** [comment]
Ah, I have now, long traceback:
Traceback (most recent call last):
  File "C:\Users\agaso\twblue\src\main.py", line 99, in <module>
    setup()
  File "C:\Users\agaso\twblue\src\main.py", line 67, in setup
    from controller import mainController
  File "C:\Users\agaso\twblue\src\controller\mainController.py", line
7, in <module>
    from wxUI import (view, dialogs, commonMessageDialogs,
sysTrayIcon)
  File "C:\Users\agaso\twblue\src\wxUI\dialogs\__init__.py", line 1,
in <module>
    import baseDialog, trends, configuration, lists, message, search,
find, show_user, update_profile, urlList, userSele
ction, utils
  File "C:\Users\agaso\twblue\src\wxUI\dialogs\search.py", line 5, in
<module>
    from extra import translator
  File "C:\Users\agaso\twblue\src\extra\translator\__init__.py", line
2, in <module>
    import translator
  File "C:\Users\agaso\twblue\src\extra\translator\translator.py",
line 2, in <module>
    from yandex_translate import YandexTranslate
ImportError: No module named yandex_translate


2017-11-09 18:43 GMT+01:00, José Manuel <notifications@github.com>:

**Comment by jmdaweb** [comment]
It seems that you don't have yandex.translate package installed. Navigate to C:\python27\scripts, and run the following command to install and upgrade all required libraries:

easy_install -Z --upgrade six configobj markdown future requests oauthlib requests-oauthlib requests-toolbelt pypubsub==3.3.0 pygeocoder arrow==0.6 python-dateutil futures winpaths PySocks win_inet_pton yandex.translate idna chardet urllib3

Regards.


El 09/11/2017 a las 18:57, agasoft escribió:
Ah, I have now, long traceback:
Traceback (most recent call last):
File "C:\Users\agaso\twblue\src\main.py", line 99, in <module>
setup()
File "C:\Users\agaso\twblue\src\main.py", line 67, in setup
from controller import mainController
File "C:\Users\agaso\twblue\src\controller\mainController.py", line
7, in <module>
from wxUI import (view, dialogs, commonMessageDialogs,
sysTrayIcon)
File "C:\Users\agaso\twblue\src\wxUI\dialogs\__init__.py", line 1,
in <module>
import baseDialog, trends, configuration, lists, message, search,
find, show_user, update_profile, urlList, userSele
ction, utils
File "C:\Users\agaso\twblue\src\wxUI\dialogs\search.py", line 5, in
<module>
from extra import translator
File "C:\Users\agaso\twblue\src\extra\translator\__init__.py", line
2, in <module>
import translator
File "C:\Users\agaso\twblue\src\extra\translator\translator.py",
line 2, in <module>
from yandex_translate import YandexTranslate
ImportError: No module named yandex_translate


2017-11-09 18:43 GMT+01:00, José Manuel <notifications@github.com><mailto:notifications@github.com>:

**Comment by codeofdusk** [comment]
Run:
Pip install yandex.translate

Bill

**Comment by agasoft** [comment]
Thanks.
Working now.
I just have one question more.
I have always opened python.exe aside, like some kind of console window.
Is this normal, or can I somehow minimize or hide it?


2017-11-09 19:13 GMT+01:00, Bill Dengler <notifications@github.com>:
> Run:
> Pip install yandex.translate
>
> Bill
>

**Comment by jmdaweb** [comment]
If you run TWBlue from source, Python window will be always there. You can minimize it, but if you close, the program is stopped.

**Comment by agasoft** [comment]
When I could expect my fixed issue in some kind of executable,
snapshots or regular one?
Thanks a lot. you can close the issue now.


2017-11-09 20:03 GMT+01:00, José Manuel <notifications@github.com>:

**Comment by jmdaweb** [comment]
The new version will arrive soon with this issue fixed. If you can't wait, you can build your own binaries following the instructions provided in readme.md.

**Comment by agasoft** [comment]
Thanks.
 I just found small hint.
If you like to hide python.exe window for showing, just rename main.py
to main.pyw
And window will never show.


2017-11-09 20:28 GMT+01:00, José Manuel <notifications@github.com>:
