### ISSUE TITLE
A Few Issues with Mention to All and Long Tweet Checkboxes

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#176]
It seems that even if twishort_enabled is false and mention_all is true in session.conf, when composing mentions, mention to all is unchecked and long tweet is checked.

**Comment by Mohamed00** [comment]
It seems mention to all is still unchecked by default...

**Comment by manuelcortez** [comment]
That's the normal behaviour. Bot mention to all and long tweet will be unchecked by default.

**Comment by Mohamed00** [comment]
Why uncheck mention to all though? It seems like it would be better to leave mention to all checked to avoid removing everyone from a conversation. I'd rather keep everyone in rather than have to delete a tweet because I forgot to check mention to all.
