### ISSUE TITLE
Coercing to Unicode Error Occurs when Expanding URL's from Several Services

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#179]
### Steps to reproduce.
1. Try to expand a URL from a shortener such as if.tt, bit.ly, or another service, example url: (leads to a Redmond Pie article) http://bit.ly/2AwczKa.
### Expected.
The URL expands and the URL the shortener redirects to is displayed.
### Actual.
The URL fails to expand and the following traceback is displayed.
Traceback (most recent call last):
  File "c:\twblue\src\controller\messages.py", line 77, in unshorten
    self.message.set_text(self.message.get_text().replace(urls[0], url_shortener.unshorten(
urls[0])))
TypeError: coercing to Unicode: need string or buffer, NoneType found.

**Comment by codeofdusk** [comment]
All of this madness should be fixed when #169 is merged.

**Comment by codeofdusk** [comment]
If you’d like to test, do

    git clone --recursive https://github.com/codeofdusk/twblue
    cd twblue
    git checkout py3

Then follow the directions at:
https://github.com/codeofdusk/TWBlue/blob/py3/README.md <https://github.com/codeofdusk/TWBlue/blob/py3/README.md>
Note that this build is somewhat untested and may have other bugs! I'm using it myself with (almost) no issues.

**Comment by jmdaweb** [comment]
Bill, we know we have to port to Python 3, but please, don't give this solution as the only available alternative! We have to know why url_shortener returns None when expanding this url.

Regards.


El 12/11/2017 a las 16:37, Bill Dengler escribió:
If you’d like to test, do
Git clone https://github.com/codeofdusk/twblue <https://github.com/codeofdusk/twblue><https://github.com/codeofdusk/twblue>
Cd twblue
Git checkout py3

Then follow the directions at:
https://github.com/codeofdusk/TWBlue/blob/py3/README.md <https://github.com/codeofdusk/TWBlue/blob/py3/README.md><https://github.com/codeofdusk/TWBlue/blob/py3/README.md>

Bill

**Comment by jmdaweb** [comment]
This is fixed, but take into account that if you try to expand an expanded URL, TWBlue might freeze for some time. Use the expand button only if you are sure that the URL is shortened.

**Comment by Mohamed00** [comment]
Hmm. It seems audio is timing out when played now. It seems to freeze the client for some time then fail to play. Trying to play it again several times doesn't help either, and the audio seems to be working.

**Comment by Mohamed00** [comment]
Disregard the previous comment. I think it was a network issue. Apologies.
