### ISSUE TITLE
Templates for modifying how TWBlue displays items in buffers

### ISSUE THREAD

**Issue by masonasons** [manuelcortez/TWBlue#180]
The ability to modify how TWBlue displays templates for each buffer separately. E.G. Home can have a different buffer than user timeline, DM, etc.

**Comment by Menelion** [comment]
@manuelcortez, do we need this? It's kind of a political decision, lots of code would need to be rewritten. There are pros and cons, of course. What do you think?

**Comment by manuelcortez** [comment]
I think for now this is not a priority, although  I'd like to keep it open for later. The main problem we have is the GUI interface at this moment. If we implement a template system that will allow everyone to choose the information a tweet will expose after being rendered and order of fields, we'd need to allow TWBlue to rebuild all lists every time a buffer gets changes in their templates, wich will mean or alot of restarts, or removing and re-adding a wx.Panel with updated information every time this is happening. I think for now it would be better to work in improving TWBlue to eat less resources (Have been thinking in converting dicts to custom classes where we'll strip unneeded information for tweets, wich should make TWBlue to require less RAM memory, but may conflict with the cache database) and reduce the final executable size (making downloadable contents like spelling correction's dictionaries, for example).
