### ISSUE TITLE
User interactions on events buffer

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#183]
You can call me bug hunter or whatever you like.
But this thing is not a bug, useful suggestion we could discuss.
It would be fine if we have possibility to get user info or have user interractions in events buffer.
For example, someone new follows me and I like to se user info, or to follow back.I need to copy user name and to follow, or chekc his/her timeline.
It will be better if we press already known shourtcut keys from events buffer and do with a user whatever we like.
See timeline, open actions dialog, see user info...

**Comment by manuelcortez** [comment]
As events buffer will disappear after August 16,as stated in #217, this option won't be implemented.
