### ISSUE TITLE
Wrong URL opening on quoted tweets

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#184]
If user A quoted user B, and user be have URL in tweet,  alt+windows+enter  opening user B tweet on Twitter,, instead to open corresponding URL given in that tweet.

**Comment by Mohamed00** [comment]
Duplicate of #167.

**Comment by Mohamed00** [comment]
It seems this issue is still open...

**Comment by agasoft** [comment]
Its solved. Will try to close it.
