### ISSUE TITLE
Retweets goes to mentions buffer

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#185]
I am not sure is it the planned feature, or issue, but have no logic from my point of view.
When someone retweets any of my tweets, I am getting it on mentions buffer.
Its just retweet, not mention and not belonging there at all.
I think that retweets are listed in events buffer or if not, you may consider adding separated retweets buffer.

**Comment by Mohamed00** [comment]
I really don't see the point. Retweets, while they are not replies, technically mention your username, so I really don't see a reason to sort retweets in to their own buffer.

**Comment by agasoft** [comment]
Everything on twitter mentioning your user name. But retweets have
nothing to do with mentions. They are only technicly mentions, as you
noticed.

2017-11-15 12:07 GMT+01:00, Mohamed Al-Hajamy <notifications@github.com>:

**Comment by manuelcortez** [comment]
All twitter clients (as far as I know) consider retweets as valid mentions. I don't see why we should change that. It's like, they mention your username and twitter endpoints mark them as mentions.
