### ISSUE TITLE
Conversations buffers not updating

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#186]
Its last for now, I promiss.
Smiles.
It seems that conversation buffers have no streamd updates, as other have.
I loaded one small conversation, and replys coming out at home or mentions buffer if I participate, but not coming on specific conversation buffer I loaded.
I  tried more times and can confirm that its happening always.

**Comment by Mohamed00** [comment]
This might be a Twitter API limitation. It seems conversations update every five minutes I believe, similar to search buffers. @manuelcortez might be able to clarify this...

**Comment by manuelcortez** [comment]
conversations cannot be provided by Streaming API, therefore they cannot be updated in real time. What all clients do for conversations is just use the Search API (part of the rest API, wich does not offer real time updates). We have a base tweet, all what we do is run a search query every 3 minutes with needed arguments for finding tweet replies. This is why we can't update conversations like if they would be part of the streaming functionality.
