### ISSUE TITLE
Sometimes twblue doesn't bring up the most recent mentions after starting

### ISSUE THREAD

**Issue by nikosdemetriou** [manuelcortez/TWBlue#188]
Using twblue snapshot on windows 7 64 bit.
I am using the default settings where tw blue doesn't stoar any tweets after exiting.
Every time I start the program, it downloads the tweets for each buffer.
Sometimes, when I start tw blue, it doesn't seam to download the latest mentions but the most recent one appears to be 6 months ago.
By restarting the program usually the problem is fixed.

**Comment by manuelcortez** [comment]
How many items did you get in this case?

**Comment by nikosdemetriou** [comment]
Hi.
I forgot to check how many were downloaded.
When it happens again I will have another look.
Thanks
Nikos

**Comment by nikosdemetriou** [comment]
Hi.
Today twblue loaded at first the most recent mentions, but after maybe 30
minutes or 1 hour, I heard the mention sound and I found 3 mentions from 6
months old again. These mentions seam to be always from the same person and
the same conversation.
I am sending you the debug log.
I don't know if you can find something useful there.
Nikos

On 20 November 2017 at 09:31, Nikos Demetriou <nikosdemetriou@googlemail.com

**Comment by nikosdemetriou** [comment]
[debug.log](https://github.com/manuelcortez/TWBlue/files/1487904/debug.log)

**Comment by nikosdemetriou** [comment]
Hi again.
The same problem happened on another machine running windows 10.
At first twblue starts fine but after a few hours 3 old mentions come up from 6 months ago.
These are the same 3 mentions that came up on the other machine.
Very strange.
Sending the log from this machine as well so hopefully it will help you.
[debug.log](https://github.com/manuelcortez/TWBlue/files/1491048/debug.log)

**Comment by nikosdemetriou** [comment]
Hi again.
After some more testing I can tell you some more details.
I have got 2 accounts with twblue.
My English account @nikosdemetriou and my Greek one @nikolaos_dem

The mistirious mentions appear on @nikosdemetriou, maybe 1 minute after I
tweet something to the @nikolaos_dem one.
I know it is very strange but this is what happens.
Thanks again
Nikos

On 20 November 2017 at 16:10, Nikos Demetriou <nikosdemetriou@googlemail.com
> wrote:

> Hi.
> Today twblue loaded at first the most recent mentions, but after maybe 30
> minutes or 1 hour, I heard the mention sound and I found 3 mentions from 6
> years old again. These mentions seam to be always from the same person and
> the same conversation.
> I am sending you the debug log.
> I don't know if you can find something useful there.
> Nikos
>
> On 20 November 2017 at 09:31, Nikos Demetriou <
