### ISSUE TITLE
About URL shorteners

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#195]
Hello,
In the past, we were using URL shortening services to allow people to shorten their URLS, so we will save some characters in a tweet. But after seeing the last tweet changes introduced in the Twitter API, I am wondering if it's still the case. So I'd like to talk about if we should allow people to shorten their URLS or just remove that feature (only shortening, so they will be able to keep expanding shorten URLS):

1. [URLS are shortened by twitter anyway,](https://developer.twitter.com/en/docs/basics/tco.html) regardless if we shorten them or no. It is not possible to change this behaviour.
2. All URLS shortened by Twitter (it means, ALL URLS) will be counted as X characters. We will have to get the value from [this endpoint](https://developer.twitter.com/en/docs/developer-utilities/configuration/api-reference/get-help-configuration) (today this value is 23 for both http and https URLS). It means if the expanded URL contains 125 characters, we should count it as 23 characters in the tweet dialog.
3. Having longer tweets (280 characters) and URLS automagically shortened in twitter, is still needed to have our own shortening services?  What are you thoughts?

**Comment by jmdaweb** [comment]
With these changes, I think shorteners could be removed safely. Most users haven't to use them nowadays. It is also good for us: less code, less libraries, and less modules to maintain.

**Comment by fastfinge** [comment]
As a user: I would support removing them. With the changes I don't need them anymore.

**Comment by smoke-j** [comment]
It is a bit redundant. no matter what twitter shortens it, so having a second shortening service without analytics doesn't make much sense. For me I don't see a reason for keeping it in the client.

**Comment by jeremyp3** [comment]
hello !

as long as it works I'm to keep the possibility to shorten the links. in fact, it is more nice to hear a little link as a link along. I find that it rallenti reading tweets

**Comment by ironcross32** [comment]
I think it could be removed without much issue or retribution from the community. If, in the rare case, you would need to shorten a link, it takes two seconds to hope over to bit.ly or your favorite shortening service, and paste it in.

**Comment by manuelcortez** [comment]
Ok, so we will do the following before completely remove URL shortening services:

1. We will make TWBlue to count URLS in tweets as 23 characters, as stated in the twitter documentation linked previously.
2. We'll enable an option in the account settings dialogue for allowing people to see a "Reduced" version of twitter URLS. Some people in twitter said that sometimes URL addresses are too long and it may ralentice the tweet reading. So with this option, they will read just a part of the URL, not the full version.
