### ISSUE TITLE
twblue is unable to load previous items from the buffer menu for a second account

### ISSUE THREAD

**Issue by nikosdemetriou** [manuelcortez/TWBlue#196]
I am using 2 twitter accounts with twblue.
For the first account in the list, twblue is able to load previous items from the buffer menu.
For the second account nothing happens if we try to load the previous items.
I am sending you my log.
Hopefully it might help.
[debug.log](https://github.com/manuelcortez/TWBlue/files/1541732/debug.log)

**Comment by nikosdemetriou** [comment]
I forgot to say that I am using the snapshot version of tw blue.
The same behaviour is happening on windows 7 and 10.
Thanks.

**Comment by manuelcortez** [comment]
For now, I can't reproduce this problem (I have three accounts in TWBlue and got more items for all of  them) and also can't get a traceback. In which buffer are you trying to get more items for the second account?

**Comment by nikosdemetriou** [comment]
Hi.
I am trying to load more items for home buffers.
For both accounts i changed the number of tweets from 100 to 200 in the
settings
Thanks
