### ISSUE TITLE
Audio Playback from Soundcloud and Audioboom is Broken

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#197]
### Steps to reproduce.
1. Try to play an audio post on Soundcloud or Audio Boom.
### Expected.
The audio should play.
### Actual.
The audio doesn't play and an unsupported file format traceback is displayed.

**Comment by manuelcortez** [comment]
Audioboo gives 503 errors at this moment.

**Comment by Mohamed00** [comment]
Soundcloud still seems to be returning 41 in some cases. Does the post have to have certain things to play?

**Comment by manuelcortez** [comment]
I think no. Just the https://soundcloud.com URL.

**Comment by Mohamed00** [comment]
Ah, OK. Must be a problem with that particular post then, the others that I've tried seem to be working.
