### ISSUE TITLE
Non-ascii character counting when composing

### ISSUE THREAD

**Issue by yncat** [manuelcortez/TWBlue#199]
There is a problem when using TWBlue as a Japanese user. 
In Twitter JP rules, Japanese characters are counted as one character, ascii character is counted as 0.5, with the maximum of 140. Since the latest stable version shows "tweet <current>/280", what I want to suggest is to count non-ascii characters as 2 chars. I don't know if there would be any side effects for this since I do not know rules of other countries, but it is absolutely true that Japanese users including me are unable to accurately count the currently written number of characters with the current implementation.

**Comment by Menelion** [comment]
Konnichiwa,  
This is a very interesting and a very tough one at the same time. Of course there will be much side effects if a non-ASCII character is counted as two.  
First of all, are you talking about Kanji or Kana characters or both? Second, who imposes those rules? If they are set by Twitter, could you or anybody speaking Japanese translate exactly what they say about Japanese characters?  
Arigato gozaimas.  
P.S. I don't speak Japanese at all (except some words), but as I'm a linguist and an IT specialist at the same time, this particular issue is very interesting for me.

**Comment by yncat** [comment]
Hello.
The fact that the 280 chars rule is not applied for Japanese can be found at
http://money.cnn.com/2017/11/07/technology/twitter-280-character-limit/index
html
I haven't read through everything though, I found an interesting article at
https://dev.twitter.com/basics/counting-characters

I'll try to explain the encoding association and the actual Japanese charact
ers shown here. There are multiple kinds of characters in Japanese: multibyt
e Hiragana, multibyte Katakana, singlebyte Katakana, multibyte Kanji, multib
yte alphabets/symbols/numbers, and ascii alphabets/symbols/numbers. the trou
blesome part is that Japanese people mix almost all of these. Singlebyte Kat
akana is rarely used; it's needed only for certain limited contexts which ar
e related to appearance. Blind users hardly use it as I've been watching so 
far. I did a quick test and found out that the ascii alphabets/symbols/numbe
rs is the only type that Twitter JP counts as 0.5 chars.
I assume that TWBlue converts Tweets into UTF-8 before posting, but I don't 
know if it is applicable for the text field because the native encoding on W
indows is UTF-16 wide character. I may be wrong for this because the wx is a
 cross platform API and there may be something that absorves the difference.
Although it is not ideal, we can just ignore the singlebyte katakana because
 it is hardly used and rather makes the problem much more complicated. Under
 this condition, checking whether a character is ascii or not effectively wo
rks at least for Japanese. However, I do know that non-Japanese characters s
uch as accents in Spanish are also in the range of non-ascii, so the approac
h above eventually ruins other regions' character counts. It might be effect
ive to get the system language from the OS and switch the behavior though.

**Comment by manuelcortez** [comment]
Hi @yncat, I'd like to give some attention to this issue. probably this can be easily solved by relying in a custom method instead of len() to count characters. Said method should count unicode normalized characters instead just the string as we do already. Is it possible for you to paste here a message, and how many characters the Twitter webapp (or an other official app) counts it, so I would have a starting point for checking if the custom algorithm will work?

**Comment by yncat** [comment]
Hello and thank you for bringing this topic back.
As I've researched, the actual strings and their counts are as follows.
* All numbers below is nn/280 in order to be accepted.
"あいうえお":10 (Japanese Hiragana, counted as 2 each)
"アイウエオ":10 (Japanese Katakana, counted as 2 each)
"ｱｲｳｴｵ":10 (Japanese Hankaku Kana, counted as 2 each)
"一二三四五":10 (Japanese number in Kanji, counted as 2 each)
"１２３４５":10 (Zenkaku number, counted as 2 each)
"12345":5 (Ascii number, counted as 2 each)
"1＊2＊3":7 (Zenkaku number + ascii *, ascii is counted as 1, non-ascii is counted as 2 each)
"ABCＡＢＣ":9 (Ascii ABC + Zenkaku ABC, ascii is counted as 1, non-ascii is counted as 2)
"ABC ＡＢＣ　ABC":15 (ascii ABC + nbsp + Zenkaku ABC + Zenkaku space + ascii ABC, Zenkaku characters are all counted as 2)
As far as I tested, it looks consistent that the count is based on whether the given character is ascii or not. The only exception is Hankaku Kana family; they're actually represented as single byte. I do not know about non-Japanese, such as Chinese or Korean.
