### ISSUE TITLE
Twishort: Support tweets over 140 characters.

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#20]
It seems the backend code to support Twishort is there, but it needs to be implemented:
Add a button to the tweet dialog to convert it to a Twishort post.
Add an option to the account settings dialog, "automatically post tweets over 140 characters as long tweets" and implement support for it.
I have no idea how to even begin, so this is definitely for you @manuelcortez

**Comment by codeofdusk** [comment]
#19 is blocking this.

**Comment by trknov** [comment]
You can implement posting to twishort, it's pretty easy, you can ask me for any help

**Comment by codeofdusk** [comment]
We did.

**Comment by trknov** [comment]
Great, thanks.
