### ISSUE TITLE
Like Tweet Keystroke Does Not Appear in Keystroke Editor 

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#200]
### Steps to reproduce.
1. Try to edit the keystroke for liking or unliking a Tweet.
### Expected.
The keystroke should appear, allowing you to edit it.
### Actual.
The keystroke doesn't appear, requiring manual edits to the .keymap file.

**Comment by manuelcortez** [comment]
i've started to work in making keystrokes more global, but I didn't closed the previous issue regarding this matter for a reason. This was just a test and that is why I just applied the change in the win10 keymap. See more about this in #181
