### ISSUE TITLE
Suggestion: Add a toggle to control whether or not new direct message or mention announcement is spoken by the screen reader

### ISSUE THREAD

**Issue by ghost** [manuelcortez/TWBlue#209]
When you receive either a direct message or a mention, an announcement is spoken by the screen reader at the same time the notification sound is played.

It seems slightly redundant to have both of these notification types play at the same time, so I think it would be useful to have a toggle to disable the speech announcement for people who just want to hear the sound.

**Comment by manuelcortez** [comment]
A few settings for disabling automatic speech or braille feedback were added in #203, perhaps that's what you were asking for?
