### ISSUE TITLE
Cannot start from source again

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#210]
A few weeks ago, I had troubles starting TW Blue from source do to VLC requirements. Its happening to me again, since last update. Here is what I am getting from the logs, I guess I need to apply some other updates too.
Traceback (most recent call last):
  File "C:\Users\agaso\twblue\src\mysc\thread_utils.py", line 13, in new_func
    func(*a, **k)
  File "C:\Users\agaso\twblue\src\sessionmanager\session.py", line 231, in api_call
    return val
UnboundLocalError: local variable 'val' referenced before assignment

**Comment by manuelcortez** [comment]
probably this happened after we merged the wxPytohn 4.0 branch in next-gen. Remove your wx installation from Windows control panel, then do pip install wxpython and you should be able to run it again.
