### ISSUE TITLE
In a proxy protected environment, update check at program launch fail close app

### ISSUE THREAD

**Issue by Nicodonald** [manuelcortez/TWBlue#212]
When I launch twblue in my enterprise environment, I see through wireshark a query to raw.githubusercontent (which is blocked if the query don't use the proxy) and the app close.
Is it possible to skip the update check because I can't set the proxy if the app don't launch

**Comment by jmdaweb** [comment]
Hi,
Now, proxy settings are applied just after starting the program, so the updater will connect via your proxy.
