### ISSUE TITLE
Migrate to the new Direct Message endpoints

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#215]
Along with the Streaming API deprecation, Twitter has released a new set of endpoints related to how users interact with direct messages. They said the current direct messages Rest API endpoints will be deprecated when the Streaming API will be gone. In order to keep TWBlue up to date, we should move everything [according to their migration guide](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration.html) and be sure it will work before the Streaming API deprecation takes place.

**Comment by Menelion** [comment]
@manuelcortez, shouldn't this one be closed? It seems, DMs work reliably now.

**Comment by manuelcortez** [comment]
hey @Menelion, apparently yes, but I still have to re-implement the delete method in Twython. I have tried the last week, though didn't worked. Twitter now accepts a delete request as opposed to post, but Twython does not support sending these requests. Once I can add it to twython and get it working I'll close this one.
