### ISSUE TITLE
Changes regarding Callback URL in Twitter Oauth

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#216]
[According to Twitter,](https://blog.twitter.com/developer/en_us/topics/tools/2018/Sign-in-with-Twitter-users-must-whitelist-callback-URLs.html) after June 12 all applications will have to witelist their callback URLS if they use the "sign in with Twitter" option to allow people to, well, sign in with Twitter. Basically that is the method we do use for avoiding the PIN codes and things we did in the past. Currently we do the authorisation process in the user's machine by creating a local server wich listens for the Auth message, and we register the URL "127.0.0.1" when calling the Auth methods. It looks this will not be possible anymore, so we'd have to send the auth responses from Twitter to a centralized server somewhere, and send the same data from the server to the client machine.

However, in the [Callback URL documentation,](https://developer.twitter.com/en/docs/basics/callback_url.html) they don't say clearly we can't witelist a local URL, like 127.0.0.1. I think I should try to witelist localhost and enable the "Calllback loking" so unauthorized access won't be allowed, wich will be the only available method after June 12. Anyway I think this may fail, more if they don't want users authorising Twitter with theyr own machines.

**Comment by manuelcortez** [comment]
At this point I'm wondering, Shall we keep going with the current "sign in with Twitter" thing, or get back to the PIN authorization code? Access levels are the same, though according to Twitter docs PIN codes may be better for Twitter clients and stuff. Personally I think would be nice to go with PIN authorization, we won't have to deal with a realtime server, getting stuff there and sending tokens to clients.

**Comment by jmdaweb** [comment]
Pin codes are a good idea to optimize resources, I would use them.
