### ISSUE TITLE
Status of mention to all and long tweet should be configurable if set to not remember

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#224]
If remember state for mention to all and long tweet is unchecked, there should be combo boxes or radio buttons configuring what they should be by default, rather than forcing the disabled by default choice so those who want them disabled can have them stay disabled and those who liked the old behavior can revert it.

**Comment by manuelcortez** [comment]
I don't think it worth the extra code. More settings added to app-settings. In that case they just can enable remembering and check them. Also by default in WX all checkboxes are unchecked.
