### ISSUE TITLE
Twitter API error when authorizing new account

### ISSUE THREAD

**Issue by aaronr7734** [manuelcortez/TWBlue#228]
I tried installing TWBlue, but after selecting yes to authorize a new account, my web browser never opened up.
After some peeking at the logs, I noticed this error:
TwythonError: Twitter API returned a 403 (Forbidden), <?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>
Not sure if it has anything to do with the upcoming API changes or what.

**Comment by sukiletxe** [comment]
I assume you're running the stable version. For TwBlue to work, you need to download a snapshot. [Get it here](https://twblue.es/pubs/snapshot.zip). If this fails (note that this is a portable version, thus you won't be able to install it, just extract it and run it), please reopen the issue and state the error you get.
