### ISSUE TITLE
Unable to Sign into Twitter with TWBlue

### ISSUE THREAD

**Issue by trodick** [manuelcortez/TWBlue#230]
I am unable to sign into Twitter using TWBlue (latest stable version, 0.93).

Steps to Reproduce:
1. Install TWBlue for the first time.
2. When the session manager opens, click New Account, then click Yes.
3. The dialog appears with the text "Waiting for account authorization..." but nothing appears in the browser. The following appears in the %APPDATA%\TW Blue\logs\debug.log file:

16/07/2018 21:06:06 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): api.twitter.com
16/07/2018 21:06:07 urllib3.connectionpool DEBUG: https://api.twitter.com:443 "GET /oauth/request_token?oauth_callback=http%3A%2F%2F127.0.0.1%3A49634 HTTP/1.1" 403 171
16/07/2018 21:06:07 mysc.thread_utils ERROR: Thread 26808 with function <bound method twitter.authorise of <twitter.twitter.twitter object at 0x00000000063AFB38>>, args of (ConfigObj({u'twitter': {u'user_key': u'', u'user_secret': u'', u'user_name': u'', u'ignored_clients': []}, u'general': {u'relative_times': True, u'max_api_calls': 1, u'max_tweets_per_call': 100, u'reverse_timelines': False, u'time_to_check_streams': 30, u'announce_stream_status': True, u'retweet_mode': u'ask', u'persist_size': 0, u'show_screen_names': False, u'buffer_order': [u'home', u'mentions', u'dm', u'sent_dm', u'sent_tweets', u'favorites', u'followers', u'friends', u'blocks', u'muted', u'events']}, u'sound': {u'volume': 1.0, u'input_device': u'Default', u'output_device': u'Default', u'session_mute': False, u'current_soundpack': u'default', u'indicate_audio': True, u'indicate_geo': True, u'indicate_img': True, u'sndup_api_key': u''}, u'other_buffers': {u'timelines': [], u'tweet_searches': [], u'lists': [], u'favourites_timelines': [], u'followers_timelines': [], u'friends_timelines': [], u'trending_topic_buffers': [], u'muted_buffers': [], u'autoread_buffers': [u'mentions', u'direct_messages', u'events']}, u'mysc': {u'spelling_language': u'', u'save_followers_in_autocompletion_db': False, u'save_friends_in_autocompletion_db': False, u'ocr_language': u''}, u'filters': {}}),), and kwargs of {} failed to run.
Traceback (most recent call last):
  File "mysc\thread_utils.pyo", line 13, in new_func
  File "twitter\twitter.pyo", line 25, in authorise
  File "twython\api.pyo", line 326, in get_authentication_tokens
TwythonError: Twitter API returned a 403 (Forbidden), <?xml version="1.0" encoding="UTF-8"?><errors><error code="415">Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings</error></errors>

This is a critical, blocking error. I have a report from another user of the same problem happening to her.

**Comment by Mohamed00** [comment]
For some reason you need to download a snapshot to authenticate. Twitter made a change to how the authentication process works that required TWBlue to revert to PIN authentication. Fortunately, you can use the snapshot to authenticate, copy your configuration from the snapshot folder to %appdata%\TW Blue and switch back to stable.

**Comment by trodick** [comment]
This would work for me, but not for users that want their client to "just work." Perhaps it would be worth pushing a maintenance release on stable that addresses this issue?

**Comment by Mohamed00** [comment]
Yeah, not sure why @manuelcortez hasn't done this.

**Comment by manuelcortez** [comment]
Code still need testing, we need to bundle VLC libs for X64, and we need to integrate latest changes for Direct messages. As this issue is related to a Stable version and Snapshot seems to fix it, I'm closing it.
