### ISSUE TITLE
add the option to schedule tweets

### ISSUE THREAD

**Issue by vlad-a-c** [manuelcortez/TWBlue#231]
i was thinking of this, and i saw that chicken nugget has that kind of thing, and i was thinking that would be a good idea for you to implement this too, because it's very usefull for streaming and stuff like this.

**Comment by rkingett** [comment]
Chicken Nugget uses Buffer to do this. I am not sure if that costs money to add, but I am hoping this can be looked into, eventually. I think we should watch to see what Twitter API 2 gives us first.
