### ISSUE TITLE
What to do with buffers for direct messages?

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#233]
According to the [new method for getting direct messages,](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events) Twitter returns both sent and received messages in reverse chronological order. Should we remove the schema of having two separate buffers or keep doing the same?

**Comment by Mohamed00** [comment]
We should probably move them to one buffer for consistency with Twitter, though I do think that could be confusing initially.

**Comment by codeofdusk** [comment]
This is consistent with other clients (for example, Nightowl on MacOS).

**Comment by manuelcortez** [comment]
OK, so, moving would be best. Are you aware there is no way of grouping them like in conversations, right? I mean in direct messages there are no conversation IDS and stuff, so we just will mix sent and received messages in one place.

**Comment by manuelcortez** [comment]
Opening it now, as people decided they want two buffers instead one.
