### ISSUE TITLE
DMs not working.

### ISSUE THREAD

**Issue by tapper82** [manuelcortez/TWBlue#242]
Hi in latest snapshot DMs will not refresh. The buffer stays emty.

**Comment by Mohamed00** [comment]
We switched to a new direct message endpoint that requires us to refresh every few minutes. If the direct messages buffer is completely empty, can you send logs please?

**Comment by tapper82** [comment]
Hi here:
https://www.dropbox.com/s/kq6gsv40vkghzoy/debug.log?dl=0
https://www.dropbox.com/s/lkbt26n101j160e/error.log?dl=0

**Comment by tapper82** [comment]
Do my logs help in any way?

**Comment by tapper82** [comment]
Hi I reinstalled and dms are working again. Thanks for looking in to it.

**Comment by manuelcortez** [comment]
Hello, it was because the cache database. If it's enabled, due to the different structure in the data for old and new direct messages, TWBlue cannot handle this situation and that's why they never load.
