### ISSUE TITLE
Sounds not playing if streaming's disabled

### ISSUE THREAD

**Issue by camaro76** [manuelcortez/TWBlue#245]
I've noticed that if you have streaming disabled, sounds are no longer playing in the home buffer or any user timeline buffer that you might have open.
They seem to play just fine for direct messages. I am not sure about mentions.

**Comment by Menelion** [comment]
Yepp, it seems, nothing is played on buffer update. Kinda confusing when you have list buffers or individual timelines open.

**Comment by manuelcortez** [comment]
Forgot to close this one, has been fixed already in the recent release.
