### ISSUE TITLE
Regarding default sounds

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#247]
From multiple threads on Twitter, I've noticed that one of the primary issues people have with TWBlue is the default soundpack. Many people have said that the current soundpack is loud, clangy and rather intrusive. And in my opinion, I agree, and I believe we need a much better soundpack as the default. Yes, the soundpack in use can be changed, absolutely, but the current one creates a negative first impression and affects people's judgement of the quality of the project. I think we need to remove the current default soundpack entirely and replace it with a new pack, with quieter and more subtle sounds. Thoughts?

**Comment by Menelion** [comment]
I tend to agree. I wouldn't say it's too loud, though, for me the volume of the sounds is too different (there are loud sounds like the greeting sound and there are too quiet sounds like the top/bottom of the buffer sound).

**Comment by codeofdusk** [comment]
A wild back, I added the classic sound pack as an option for all installations. Any thoughts on that option? Perhaps we could make that the default again?

Bill

**Comment by Mohamed00** [comment]
Yeah, that soundpack is actually not that bad. Maybe it should be the default again.

**Comment by manuelcortez** [comment]
Sounds a good idea. I think we should do that and see what will happen in snapshots, as usual.

**Comment by Mohamed00** [comment]
Though I think some of the sounds in that pack could be better, such as the like tweet, new follower and mentions sounds. Also the audio tweet sound should be converted to mono, it's panned a bit to the right for some reason and that seems really out of place.

**Comment by manuelcortez** [comment]
@Mohamed00 do you know howto do that? I don't know anything  regarding sounds, to be honest.

**Comment by Mohamed00** [comment]
Yes. I'll convert it in a bit.

**Comment by manuelcortez** [comment]
Regarding a possible new default soundpack, What about the one created by [Andre Louis?](https://twitter.com/FreakyFwoof) If you can give it a try and let me know your thoughts, it's at [This link.](https://t.co/M9opUusIzV) I've asked him and he said he is agree in making his pack the default, in case everyone here is agree. Personally I liked it and think it can be what we need.

**Comment by codeofdusk** [comment]
I think at least including it as an option (like what I did for classic/qwitter) isn’t controversial at all, so we should at least do that.
Also, if we make this new pack the default, will we keep the old one around under a different name? Maybe next-gen?

Bill

**Comment by Mohamed00** [comment]
I'd vote yes, make this the default, though probably keep the old one 
around somewhere, either as a pack named next gen as @codeofdusk said, 
or as a download on the site. I'm curious why a link to download new 
soundpacks in the help menu isn't included already, actually.

**Comment by manuelcortez** [comment]
So:

* Let's add the new pack as a new option,and ask everyone wether it should be the default in the next stable or it will keep being an option.
* The "default"pack will be renamed to next-gen, if the new pack will be the default one.
* Let's add an item in the help menu for sending everyone to the soundpacks section in the website.

**Comment by burakyuksek** [comment]
I think this default pack is better than the old one. Sounds more modern.

**Comment by codeofdusk** [comment]
We should also be careful to avoid breaking user configs (if "default" is the configured sound pack before the update, change it to next-gen so current users aren't unexpectedly switched to the new pack).

**Comment by Mohamed00** [comment]
Any updates on making the new pack the default?
