### ISSUE TITLE
There is no sound when a list or individual timeline updates

### ISSUE THREAD

**Issue by Menelion** [manuelcortez/TWBlue#252]
I have two additional buffers opened, one for a list and one for a user's timeline. There is no sound when tweets come to these buffers.  
Latest commit, running from source, classic sound pack.  
If someone guides me a bit where to fix it, I'd send a PR, I'm still learning the codebase. Thanks!

**Comment by manuelcortez** [comment]
Strange, it should work as is working in the default (still) pack. I have a timeline open and it sounds whenever a new tweet comes in. Can you change the pack and see if you get something? I'll take a look to some code anyway.

**Comment by Menelion** [comment]
Sorry, it seems, that doesn't help. And the error log is empty, also.
