### ISSUE TITLE
tweets longer than 140 characters are not expanded when added to the sent tweets buffer

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#253]
### Steps to reproduce.
1. Sent a tweet longer than 140 characters.
### Expected.
The full text of the tweet should be added to the sent tweets buffer.
### Actual.
The tweet is added with an i/web link to the sent tweets buffer, and must be viewed to show the full text.

**Comment by manuelcortez** [comment]
Hi, In the [Post tweet API documentation](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update.html) they do not specify if what they return is an extended tweet or a normal tweet. Extended tweets can be long tweets and quoted tweets. Apparently they just return a normal, old stile tweets. We can use [statuses/show](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-show-id) to get the tweet with extended properties just after we post it to Twitter, as this endpoint is less restrictive. Thoughts?

**Comment by Mohamed00** [comment]
I would say yes, the rate limit on that endpoint is pretty generous.

**Comment by manuelcortez** [comment]
It would be nice to have some tests before closing this issue.
