### ISSUE TITLE
A new buffer for retweets

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#254]
The Twitter API apparently allows us to retrieve the retweets others have done in the current user's tweets. As people have been asking regarding retweets, likes and quotes, I think we can implement a new buffer for putting retweets. Thoughts?

**Comment by Mohamed00** [comment]
Personally, I think retweets should still be considered mentions since 
they mention the user. Putting them in a buffer seems like it would 
result in fragmentation to me.

**Comment by codeofdusk** [comment]
Some people are retweeting tweets by tweeting a link to them. Those types of retweets are not mentions as they are not retweets in the true sense.

Bill

**Comment by manuelcortez** [comment]
Hi, apparently there is no way (without running out of API calls) to get retweet. The most similar approach is getting all of your tweets that has been retweeted, then iterate and call a function for getting the full retweet (including the user who did the retweet). Closing.
