### ISSUE TITLE
New Buffer Suggestion: List of Users that another User is Following

### ISSUE THREAD

**Issue by elliott94** [manuelcortez/TWBlue#258]
Back in the days of Qwitter, it used to be possible to obtain a list of the users that another user (either one of the people that you were following or one of your followers) was following - this data would be placed into its own buffer. Would it be possible to add something like this to TWBlue, or is this no longer possible due to API limitations?

**Comment by jmdaweb** [comment]
Hello.
You can find this feature in the open timeline dialog. Type the user name, then press tab. You will see a group of radio buttons. Choose tweets, likes, friends or followers.
Regards.
