### ISSUE TITLE
Refactor "report an error"

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#26]
I think we need to rewrite the "report an error" system. Perhaps just have the default browser open http://github.com/manuelcortez/twblue/issues/new so users can input issues directly into Github?

**Comment by manuelcortez** [comment]
No, as I know, this is not possible because anonimous users can't file bugs in github. We're using mantis for doing this job.

**Comment by codeofdusk** [comment]
Anonymous users shouldn’t be able to create issues. Then they can’t manage/respond to them.
Why don't we use one issue tracker for everything? This one is integrated with version control, so isn't it easiest to just use this?

**Comment by codeofdusk** [comment]
Should we use Mantis for filing everything?

**Comment by manuelcortez** [comment]
I don't know. Mantis is not integrated with github, but all users should be able to report bugs. I think we should use github for managing bugs related to the code, but mantis for user reports.

**Comment by codeofdusk** [comment]
Why not set up http://gitreports.com
