### ISSUE TITLE
GUI: Remember Position when exiting TWBlue

### ISSUE THREAD

**Issue by elliott94** [manuelcortez/TWBlue#262]
For users who prefer to use the GUI rather than the global hotkeys, would it be possible to remember the position of the cursor when focused on the GUI at the time of exiting the software? This would be useful in situations when reading long lists of tweets.

**Comment by manuelcortez** [comment]
Are you using the database cache already? this should work if works in the invisible interface (after all, the invisible interface is the GUI interface being navigated programmatically).

**Comment by elliott94** [comment]
This now appears to be working - apologies for the trouble.
