### ISSUE TITLE
GUI: Allow the Skipping of Tweets with Page Up/Down

### ISSUE THREAD

**Issue by elliott94** [manuelcortez/TWBlue#263]
Currently, when using the GUI to read through tweets it's not possible to use either Page Up/Down to quickly skip tweets. Could this possibly be added, with maybe a configurable option for the number of tweets that this key would skip?

**Comment by manuelcortez** [comment]
It works so for me, if you're in the list you can easily do that exactly.

**Comment by elliott94** [comment]
Interestingly, this doesn't work for me. My keyboard doesn't have page up/down keys - these are being remapped, could this be the issue/ When you do this, how many tweets do you jump by?
