### ISSUE TITLE
Impossible to select all with CTRL+a when composing or replying to a direct message and running on Windows 7 or 8

### ISSUE THREAD

**Issue by lukaszgo1** [manuelcortez/TWBlue#269]
## to reproduce:
1. Start composing a direct message or replying to an existing one.
2. Type some text.
3. Press CTRL+A in hopes of selecting all.
## expected
The entire content of an edit box should be selected.
## actual
The Windows ding is played.

**Comment by Mohamed00** [comment]
Odd. I'm unable to reproduce this, however you may be able to select all by right clicking.

**Comment by lukaszgo1** [comment]
Further testing shows, that this bug is present only on Windows 7 and 8. Will test on 8.1 when possible. @Mohamed00  What version of Windows are you using?

**Comment by manuelcortez** [comment]
Unfortunately this doesn't seem to be easy to be reproduced. I have tried it in a Windows 7 VM (locale in Spanish) and it worked. anyway the're little we could do about it. In sources, the accel keys are correctly defined and everything else is up to WX Widgets.

**Comment by lukaszgo1** [comment]
Just for completeness i am able to reproduce it with clean install of Windows 7 with all locale set to English and with fresh config of TWBlue.

**Comment by Mohamed00** [comment]
I'm using the latest Windows 10 insider preview and haven't been able to 
reproduce it there.
