### ISSUE TITLE
Updating portable versions of TWBlue shouldn't require administrative privileges

### ISSUE THREAD

**Issue by lukaszgo1** [manuelcortez/TWBlue#270]
to reproduce the problem
1. download [latest snapshot linked on your page](https://twblue.es/pubs/snapshot.zip)
2. login to account without administrative privileges.
3. unpack the .zip file to the location to which this user has read-write permissions.
4. Start TWBlue.exe
5. Agree to the downloading of the update.
## expected.
The update should be downloaded and performed without UAC dialog appearing.
## actual
the UAC dialog appears asking for administrator password.
It is problematic not only because the user might want to use a portable version due to lack of the admin permissions to install,, but also because the resulting TWBlue session which starts after update is started as a elevated user preventing NVDA and i believe other screen readers from accurately reading the window.

**Comment by manuelcortez** [comment]
As far as I know, making this change would require us to ship a different version of bootstrap.exe, wich would not be possible at the current moment. @jmdaweb probably may give us some light here.

**Comment by manuelcortez** [comment]
Closing as is not possible to fix it right now (would required to maintain two versions of bootstrap.exe apparently).
