### ISSUE TITLE
non-English characters after a URL are stripped and disappear

### ISSUE THREAD

**Issue by yncat** [manuelcortez/TWBlue#272]
I found an issue about auto URL detection. Here are the details:
Issue: If there is a URL in a tweet and non-English characters follow after that without a space, everything after the URL is stripped and never read. I reproduced this issue in Japanese.
Examples:
"This is just a test if my tweet including a URL like groups.io is properly parsed in TWBlue." -- works
"これは、TWBLUEがgroups.ioのようなURLを含むツイートを正しくパースできるかどうかのテストです。" -- Bugged and becomes "これは、TWBLUEがhttps://groups.io"
Additional info:
- When I press ctrl+win+enter on the bugged tweet and open the URL, groups.io is opened. So, the URL detection itself is fine.
- Inserting a space (nbsp) after the URL prevents this issue, even Japanese follows.

**Comment by manuelcortez** [comment]
Hi there, shall this issue be closed? I am unable to reproduce this problem after we fixed #305. If I paste the text you provided in the example TWBlue reads:
"これは、TWBLUEがhttp://groups.ioのようなURLを含むツイートを正しくパースできるかどうかのテストです。"
Is it supposed to b that way?

**Comment by yncat** [comment]
Hello.
Thank you for fixing it. It's exactly right!
