### ISSUE TITLE
Drop support to Windows XP

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#274]
Regarding to the change to Python 3, which should be finished some day in the next year, I think it would be appropiate to bring this issue to the discussion. I have been reading certain users complaining or reporting errors related to VLC'S components, which are no longer compatible with XP. Apparently they still work, but shows errors related to libvlc.dll and libvlccore.dll. I always reply they are not "our own" components, therefore they are unable to be fixed in our side.

I consider dropping support for Windows XP officially as soon as we will be able to generate the first build from Python 3, and can assure such build works normally for everyone using modern windows. Otherwise we would have to check for compatibility issues and stick to Python 3.4, which is the last version supporting Windows XP, but still would have issues if one of the dependencies refuses to work under that windows version. I planned to announce the goals for the next year in TWBlue (basically python 3 compatibility and Mastodon integration) and write something regarding stop ensuring compatibility in Windows XP within the next year, unless someone here has something to say in this subject.

**Comment by Mohamed00** [comment]
I'd say yes, drop support for XP officially at some point next year. 
It's been unsupported by Microsoft for years now.

**Comment by lcornwell1** [comment]
I think that stopping xp stuff would be  a great thing.

-----Original Message-----

**Comment by manuelcortez** [comment]
Hey there, As I've announced [Here,](https://manuelcortez.net/blog/post/moving-python-3.html) this next release of TWBlue (0.95 I believe) will be the last one supporting Windows XP. Right after this version, We'll start to work in new snapshot generation with a Python 3 compatible codebase so we can conduct some testing before a new stable release.

**Comment by mirh** [comment]
For the very records, there are more or less updated versions of python 3 for XP if you check MSFN forums. 
And as for VLC, not sure how much the lack of "official" support is going to matter

**Comment by manuelcortez** [comment]
Indeed there is some kind of unofficial support, though that's definitely a route we don't want to go. I consider we have already enough workload to keep code updated and working with all modules we use. If someone decides to take the time to run and build the sources of the project in XP I'd link his/her results happily, but I'm not able to do that :).
