### ISSUE TITLE
TwBlue should not allow multiple instances

### ISSUE THREAD

**Issue by burakyuksek** [manuelcortez/TWBlue#278]
Hello,
Since there is a mutli account feature, I don't think there is any point allowing multiple instances of the program. When you launch a second instance the first instance becomes unusable anyway.

**Comment by codeofdusk** [comment]
Yes, this makes the most sense to me.

Implementation thoughts:

* In the user config directory, create a file, named application.name+".pid", containing the process ID of the started instance.
* On launch, check if the current PID matches that in the file (if it exists). If not, exit (possibly with an error) if the PID exists on the system. If it doesn't, delete the file and show a message to the user (application quit unexpectedly, maybe report an issue).
* If the file doesn't exist, create it and fill in the PID.
* On (graceful) exit, delete the file.

I should be able to do this.
