### ISSUE TITLE
Timelines are not correctly named and displayed

### ISSUE THREAD

**Issue by alexbernier** [manuelcortez/TWBlue#281]
Hi,
Since January 24, I face some issues with the timelines :
* Timielines are named using a sequence of numbers (instead of the usual
hashtag or user name)
* The timelines doesn't open automatically anymore (we should manually use the
"Updating buffer" item in the Buffer menu)

Best wishes,

Alex

**Comment by manuelcortez** [comment]
Hi,
How many timelines you have configured in your account? Does it happen 
all the time or occasionally?

**Comment by alexbernier** [comment]
I have 51 timelines configured in my account.
3 timelines are still correctly named.
48 are named using a sequence of numbers.

Best wishes,

Alex

**Comment by Mohamed00** [comment]
51 timelines? With that many you'd run out of API calls in seconds. Can 
you send your logs?

**Comment by alexbernier** [comment]
Hi,


All is OK now. I think that the problem was caused by a timeline (the first one of the list) which was related to a user who has renamed his username. Removing this timeline solved the problem.


Alex
