### ISSUE TITLE
Traceback occurs when using accessible_output2 from requirements.txt

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#282]
### Steps to reproduce.
Try to use the invisible interface while using accessible_output2 from requirements.txt.
### Expected.
Text is spoken.
### Actual.
No text is spoken and the following traceback is displayed.
Traceback (most recent call last):
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 70, in <lambda>
    self.parent.Bind(wx.EVT_HOTKEY, lambda evt: self.process_key(evt, key_id), id=key_id)
  File "C:\twblue\src\keyboard_handler\wx_handler.py", line 88, in process_key
    self.handle_key(i)
  File "C:\twblue\src\keyboard_handler\main.py", line 47, in handle_key
    return function()
  File "C:\twblue\src\controller\mainController.py", line 1124, in right
    output.speak(msg, True)
  File "C:\twblue\src\output.py", line 15, in speak
    speaker.speak(text, interrupt)
AttributeError: 'NoneType' object has no attribute 'speak'

**Comment by jmdaweb** [comment]
Does the accessible_output2 package include the required dlls?

Regards.

**Comment by Mohamed00** [comment]
Apparently it does.

**Comment by manuelcortez** [comment]
@jmdaweb perhaps it has something to do with generation of the com_cache? If that throws any error during import time probably accessible_output2 will refuse to work properly. I cannot reproduce the error in my machine, however.

**Comment by Mohamed00** [comment]
The error still occurs even when the com_cache is cleared.

**Comment by lukaszgo1** [comment]
I am also experiencing this.

**Comment by lukaszgo1** [comment]
I've tried on two different systems on one I've installed Python 32-bit on one 64-bit and the error is present on  both. The Python and any other TWBlue dependencies was  never installed on either of the systems.

**Comment by lukaszgo1** [comment]
@manuelcortez One test which would show if the errors is on our machines or in the TWBlue code would be to trigger an AppVeyor build of the current master, and then check how the created build would behave. Would it be possible to do it?

**Comment by manuelcortez** [comment]
@lukaszgo1 Sure, I'll try to finish some work today or tomorrow in the morning so we can give it a try.

**Comment by manuelcortez** [comment]
OK, as promised, I have generated a few new snapshots. There was an error in setup.py, as we were including all DLLS from Accessible_output2 by using a glob function. I replaced it by the correct call to accessible_output2.find_datafiles(), that made the setup script to include the real libraries in the correct path. But everything else worked normally and no errors were detected inside accessible_output2.

**Comment by Mohamed00** [comment]
It's still happening on the latest version, I tried clearing com_cache 
with no effect.

**Comment by sukiletxe** [comment]
Now the traceback changes:
```
20/02/2019 11:14:28 core.output ERROR: Output: Error during initialization.
Traceback (most recent call last):
  File "output.pyo", line 25, in setup
  File "accessible_output2\outputs\auto.pyo", line 12, in __init__
  File "accessible_output2\outputs\jaws.pyo", line 16, in __init__
  File "libloader\com.pyo", line 15, in load_com
  File "win32com\client\gencache.pyo", line 534, in EnsureDispatch
  File "win32com\client\gencache.pyo", line 518, in EnsureModule
  File "win32com\client\gencache.pyo", line 287, in MakeModuleForTypelib
  File "win32com\client\makepy.pyo", line 286, in GenerateFromTypeLibSpec
  File "win32com\client\gencache.pyo", line 548, in AddModuleToCache
  File "win32com\client\gencache.pyo", line 627, in _GetModule
ImportError: No module named F152C4EF-B92F-4139-A901-E8F1E28CC8E0x0x1x0
```
Environment: Deleted com_cache folder, latest snapshot (13).

**Comment by manuelcortez** [comment]
@sukiletxe, could you load the full debug.log somewhere and send it to me? I'm interested in checking how the fixes for libloaded are applied, just in case they are. You can paste it here or in a DM to my account.

**Comment by sukiletxe** [comment]
Here it is, after deleting `com_cache` and `logs` folders, and starting TwBlue and waiting until it's ready:
https://1drv.ms/u/s!AoR_kDEmAgXSiq8gl-C8Ul6eCTZepw

**Comment by manuelcortez** [comment]
@sukiletxe and everyone else having this issue, I've uploaded a new generated version [here.](https://twblue.es/snapshot.zip) Could you give it a try and, in case the error still is the same, paste the debug.log file?

**Comment by sukiletxe** [comment]
Same traceback. As `stderr.log` contains text too, here is the folder, in 7z:
https://1drv.ms/u/s!AoR_kDEmAgXSiq8iMQHMm8oocN2yMQ

**Comment by Mohamed00** [comment]
Not sure if this has anything to do with it, but the old version of accessible_output2 I provided in a previous comment still seems to work.

**Comment by manuelcortez** [comment]
@Mohamed00 Could you fork https://github.com/manuelcortez/accessible_output2 and replace the module there? I'd like to point to your fork in requirements and see how, and most important why, it works in the old version but not in the newer package.

**Comment by Mohamed00** [comment]
The old version has been added to my fork of the repository.

**Comment by manuelcortez** [comment]
Could you try the snapshot version from the Link I provided a few comments ago?

**Comment by Mohamed00** [comment]
It's working now.

**Comment by manuelcortez** [comment]
Awesome. Will try to fix the other bug about sound_lib and will update the version file.

**Comment by Mohamed00** [comment]
So should I keep this fork online?

**Comment by manuelcortez** [comment]
you can send a pr to the base repo so I can merge it.

**Comment by Mohamed00** [comment]
PR created.
