### ISSUE TITLE
Traceback occurs when attempting to record audio

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#284]
### Steps to reproduce.
Try to record audio from the attach audio dialog.
### Expected.
Audio is recorded.
### Actual.
Audio is not recorded and the following traceback is displayed.
Traceback (most recent call last):
  File "c:\twblue\src\extra\AudioUploader\audioUploader.py", line 83, in on_record
    self.start_recording()
  File "c:\twblue\src\extra\AudioUploader\audioUploader.py", line 89, in start_recording
    self.recording = sound.recording(self.file)
  File "c:\twblue\src\sound.py", line 43, in recording
    val = sound_lib.recording.WaveRecording(filename=filename)
AttributeError: 'module' object has no attribute 'recording'

**Comment by manuelcortez** [comment]
@Mohamed00, can you confirm the bug has been fixed in the last generated version? the link is always the same. Though I will trigger an update for everyone as soon as this is fixed.

**Comment by Mohamed00** [comment]
It's fixed, thanks.
