### ISSUE TITLE
Broken JAWS speach in invisible interface  in last snapshots

### ISSUE THREAD

**Issue by agasoft** [manuelcortez/TWBlue#285]
From snapshot version 13, JAWS not reading invisible interface anymore. I know that its known issue, but still not open here. So just want to discuss  about it. I hope that I am not only one with this problem and maybe someone found workaround?

**Comment by lukaszgo1** [comment]
@agasoft Have you tried the latest snapshot 18? For me on Windows 7 and with Jaws 2018 speech works in the invisible interface.
