### ISSUE TITLE
Switching codebase to python 3

### ISSUE THREAD

**Issue by JessicaTegner** [manuelcortez/TWBlue#288]
Hi.
First of all amazing software.
I am currently running on a test branch of twblue
 that runs on python 3, do you @manuelcortez  just wan't me to make a pr with my changes or something (nothing breaks or anything)

**Comment by manuelcortez** [comment]
Hi,
Does the codebase work both under Python 2 and 3? We're very close to a next stable and while I do appreciate the move, we need to be sure nothing will be broken when using it for Pytohn 2, as i guess the next two versions will be built Under py2.

**Comment by JessicaTegner** [comment]
Hi.
No, the code are not compatible with py2 since it's deprecated, however it works fine under py3.7 (as I said in my original post) and I also redirected the stdout and stderr if running from a console, to make debugging and implementing new features easyer.
@manuelcortez

**Comment by manuelcortez** [comment]
closing as the code has evolved since this issue and now it supports Python 3.
