### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by burakyuksek** [manuelcortez/TWBlue#295]
Hello,
The shortcuts "view item on twitter" and "play sound" conflict in the default keymap.

**Comment by trypsynth** [comment]
I realize this issue is old, but @burakyuksek, could you please be more specific (i.e. what key doesn't work)?

**Comment by burakyuksek** [comment]
Hello,
I'm sorry, this was a mistake on my part. I switched to windows10 recently at that time and I thought the keys used for playing audio and viewing the item on Twitter conflicted. This is not the case. I'm closing the issue.
