### ISSUE TITLE
Japanese has been lost from the "translate into" list

### ISSUE THREAD

**Issue by yncat** [manuelcortez/TWBlue#297]

**Comment by Mohamed00** [comment]
Isn't the list of languages fetched from the translation provider? If so, I think they may have removed the option.

**Comment by yncat** [comment]
I looked at the source. It has supported languages hardcoded, but also retrieves available languages from the translation provider under some circumstances. I do not know how they are used.

**Comment by manuelcortez** [comment]
hello there, thanks for the report and sorry for the long time with no answers from here. The languages are hardcoded for translation purposes only, but all supported languages for translations are retrieved automatically the first time the function available_languages is called. Later the module uses the cached languages that have been retrieved already. Unfortunately yandex.translate no longer returns Japanese as an available language, though I'm not sure if this is an error on their end or if they have decided to drop support for translation into Japanese from their developer API.
If you know of any translation service that can work with Japanese and is free to use for developers, or has a relatively high volume of characters per month (Yandex has 20 billion before charging, for example), I'd love to take a look and add it as an alternative.

**Comment by manuelcortez** [comment]
Closing for now, will reopen it if there are any alternatives to yandex for japanese.
