### ISSUE TITLE
error when opening TW Blue Win7 64bit

### ISSUE THREAD

**Issue by sparkeymarky** [manuelcortez/TWBlue#3]
![screenshot 2014-12-11 04 53 02](https://cloud.githubusercontent.com/assets/10150413/5389356/ef5b52a4-80f2-11e4-9b05-cda89ed849d4.png)

**Comment by codeofdusk** [comment]
No response received, so closing. If you're still encountering the error, please reopen with a detailed set of steps to reproduce.
