### ISSUE TITLE
In tweet and DM. Ne

### ISSUE THREAD

**Issue by smoke-j** [manuelcortez/TWBlue#305]
This has been happening for quite a long time. If you use shift enter to insert a new line into a tweet the first word of a new line is cut off, and sometimes it won't even send the new line in the tweet or DM at all. This happens both with the gui shown or hidden.
for example, the below tweet would be what is written and sent.
"here is the first line of text.
Here is the second line of text."
What would be seen on TW Blue is.
"Here is the first line of text. is the second line of text."
or it will read:
"Here is the first line of text.
is the second line of text."

This has also happened if I send out something via Buffer, when reading it back on TW Blue it cuts off the first word in a new line. Viewing the tweet on twitter.com shows the whole message.

**Comment by jmdaweb** [comment]
I can't reproduce it. I have sent a tweet with multiple lines and TWBlue displays it as expected in both invisible and visible modes.

**Comment by smoke-j** [comment]
Sorry if this double sends, I sent a reply to the email and it doesn't seem to have gone through.

it is caused by a url at the end of the above line.

for example.

one two www.google.com
three four five

results in

one two www.google.com four five

it happens when there is a new line after a url, the first word in that new line is removed and the new line is turned into a space.

update: if you add a space after the URL then the new line works with no deleting of the first word in the new line.

**Comment by manuelcortez** [comment]
hey there, I Have reproduced it, that's probably due to the regexp used to detect URLS, I'll take a look and see what we can do. Thanks for the report!
