### ISSUE TITLE
Python 3: Generate executable versions of TWBlue

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#309]
I believe it's time to start to think a new module for generating the distributable bundles of TWBlue as we are slowly fixing all critical errors present in the Python 3 compatible code, and would be nice to start the snapshot process again so people would be able to give us more feedback and report bugs. Personally, I have some experience with Pytohn 3 and pyinstaller, as this is the module I already use in other projects such as Socializer, MusicDL and a few other private stuff. I think I may start writing the spec file and generate some testing versions with the CI environment very soon.

**Comment by manuelcortez** [comment]
hey guys, I have finished the script for pyinstaller, and also updated the appveyor CI script, so I have generated a snapshot version by using the Python 3 stack. I have used the latest 3.7 version of Python and the appveyor platform. Could you please try to run this file so we can see if we can generate a snapshot for everyone? [this is the link to the Python 3 snapshot.](https://twblue.es/pubs/snapshot_python3.zip) So far there are no changes besides this version being built with Py3.

**Comment by JessicaTegner** [comment]
I can confirm that the snapshot provided works on my machine.

* Windows 10 (version 1909 64 bit)

The interesting thing to note however was, that when extracting the archive, windows defender took twblue.exe as a virus.

**Comment by lcornwell1** [comment]
Hey there, to all I am getting a message about my data bace needing to be to be built and I don’t know why could someone please  help ?.

**Comment by manuelcortez** [comment]
Update on this issue:

* I have changed the building module to cx_freeze, because pyinstaller was flagged by too many antivirus software vendors and that was making the process too painful to be efficient or purchasing a code signing cert.
* The new file to reference is again src/setup.py and it should be working for building a new executable soon. right now the only problem we have is enchant and its 3.0.1 version, which does not work well when packaged with cx_freeze.

**Comment by akash07k** [comment]
Hey bro,
@manuelcortez 
So, the python3 based snapshots are getting released on regular basis? Can I always download the latest updates from the below URL? and will we get the automatic updates for the python3 based snapshots?
https://twblue.es/pubs/snapshot_python3.zip
> Update on this issue:
> 
> * I have changed the building module to cx_freeze, because pyinstaller was flagged by too many antivirus software vendors and that was making the process too painful to be efficient or purchasing a code signing cert.
> * The new file to reference is again src/setup.py and it should be working for building a new executable soon. right now the only problem we have is enchant and its 3.0.1 version, which does not work well when packaged with cx_freeze.

**Comment by rkingett** [comment]
Glad to see these changes!

**Comment by manuelcortez** [comment]
As we are already building a snapshot [here](https://twblue.es/pubs/snapshot.zip) I am closing this now.
