### ISSUE TITLE
buffers stop updating automatically

### ISSUE THREAD

**Issue by Shadowcat42** [manuelcortez/TWBlue#313]
First off, my apologies in advance if this has already been fixed in the newest snapshots, but I haven't seen anything about it.
I do not know what causes this, unfortunately. But on version 0.95 currently, and on occasion my buffers will just... stop automatically updating and I have to manually trigger them if I want to see anything. I don't get any error messages, it just seems to happen. Restarting the program seems to fix it though. This applies to both home and direct messages. In the case of the DM I'd missed, it was from 2 hours ago once I ran the buffer update.

**Comment by manuelcortez** [comment]
hello there, thank you for the report. could you send us the log files the next time you see it, so we can take a look to the problem?

**Comment by Shadowcat42** [comment]
It actually seems to have stopped on its own, although I'm honestly
not sure how. But I haven't seen it at all recently. What I can add
though is it seems to have something to do with manually updating
buffers, if I never do that then I don't see this. But even then, it
doesn't happen every time I update manually either so it's quite an
odd thing.

**Comment by lcornwell1** [comment]
Hey there, to all I am having trouble with my twblue  it sometimes stops working or when I start it up itwill not run can some one please tell me how to fix this?    from: Ryan Chou <notifications@github.com> 
Sent: Sunday, October 6, 2019 11:52 AM
To: manuelcortez/TWBlue <TWBlue@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [manuelcortez/TWBlue] buffers stop updating automatically (#313)

 

It actually seems to have stopped on its own, although I'm honestly
not sure how. But I haven't seen it at all recently. What I can add
though is it seems to have something to do with manually updating
buffers, if I never do that then I don't see this. But even then, it
doesn't happen every time I update manually either so it's quite an
odd thing.
