### ISSUE TITLE
TW Blue refuses to start

### ISSUE THREAD

**Issue by jolomigeorge** [manuelcortez/TWBlue#316]
each time i click on the TW Blue icon on my desktop, the option to donate or not to donate to TW Blue comes up and if i click on no, the donate dialogue goes away but the TW Blue will not start. if i click on yes, a page on my browser opens to donate. i need the TW Blue app to run on my windows 10 pc. what do i do?

**Comment by manuelcortez** [comment]
Hi there, could you paste the content of your logs so we can take a look and see what is causing your  issue? If you are using a portable version, there is a "logs" folder created in the same directory where TWBlue has its files. In case you're using an installed copy, logs are in the TWBlue folder, inside the "appdata" directory (to get there press windows+R, type %appdata% and press enter).

**Comment by jolomigeorge** [comment]
ok... i'll copy it here. i'm currently using the portable version and i saw about 4 txt files in the log folder, so i'll copy all here...
here are the content of all four files in saw in the log folder:
Log file 1.
debug
05/10/2019 03:53:18 main DEBUG: Starting TWBlue 0.95
05/10/2019 03:53:18 config DEBUG: Loading global app settings...
05/10/2019 03:53:19 config DEBUG: Loading keymap...
05/10/2019 03:53:19 main DEBUG: Using Windows 64bit
05/10/2019 03:53:19 main DEBUG: Application path is C:\Downloads\Software\twblue-latest_x64
05/10/2019 03:53:19 main DEBUG: config path  is C:\Downloads\Software\twblue-latest_x64\config
05/10/2019 03:53:19 sound DEBUG: creating stream URL player...
05/10/2019 03:53:19 sound DEBUG: URL Player initialized
05/10/2019 03:53:22 fixes.fix_libloader DEBUG: Applying fix for Libloader...
05/10/2019 03:53:22 fixes.fix_libloader DEBUG: Load_com has been mapped correctly.
05/10/2019 03:53:22 core.output DEBUG: Initializing output subsystem.
05/10/2019 03:53:37 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): twblue.es:443
05/10/2019 03:53:37 updater ERROR: Update failed! Using mirror URL...
05/10/2019 03:53:37 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): raw.githubusercontent.com:443
05/10/2019 03:53:37 updater ERROR: Update failed.
Traceback (most recent call last):
  File "update\updater.pyo", line 14, in do_update
  File "update\update.pyo", line 22, in perform_update
  File "update\update.pyo", line 58, in find_update
  File "requests\sessions.pyo", line 546, in get
  File "requests\sessions.pyo", line 533, in request
  File "requests\sessions.pyo", line 646, in send
  File "requests\adapters.pyo", line 516, in send
ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /manuelcortez/TWBlue/next-gen/updates/stable.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000066F4C18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))

Log file 2.
Error
05/10/2019 03:53:37 updater ERROR: Update failed! Using mirror URL...
05/10/2019 03:53:37 updater ERROR: Update failed.
Traceback (most recent call last):
  File "update\updater.pyo", line 14, in do_update
  File "update\update.pyo", line 22, in perform_update
  File "update\update.pyo", line 58, in find_update
  File "requests\sessions.pyo", line 546, in get
  File "requests\sessions.pyo", line 533, in request
  File "requests\sessions.pyo", line 646, in send
  File "requests\adapters.pyo", line 516, in send
ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /manuelcortez/TWBlue/next-gen/updates/stable.json (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000000066F4C18>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
Log file 3.
Stdout
Rebuilding cache of generated files for COM support...
Checking C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4
Checking F152C4EF-B92F-4139-A901-E8F1E28CC8E0x0x1x0
Done.
Log file 4.
Stderr
Traceback (most recent call last):
  File "main.py", line 130, in <module>
  File "main.py", line 82, in setup
  File "update\updater.pyo", line 18, in do_update
  File "update\updater.pyo", line 22, in do_update
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by manuelcortez** [comment]
do you have internet connection in that computer? TWBlue cannot connect to the official website for checking for updates, but strange is that also is unable to connect to github to the Mirror URL.
