### ISSUE TITLE
python3 packaging & why yandex.translate?

### ISSUE THREAD

**Issue by ghost** [manuelcortez/TWBlue#320]
Hi Twitter birds,

I tested TB from the python3 branch.
Seems to be working fine.

Py2exe has been adapted to python3, we have a packaging solution for Python3.
 https://github.com/albertosottile/py2exe
This repo is actively used in NVDA's 2019.3 release.

There's another topic.
Yandex.translate's translations are not good.
Why don't we use google.translate?
Is there an explanation for this?

I can replace yandex.translate with google.translate if we don't have a valid reason
A PR would be perfect.

@manuelcortez ,  What do you say?

**Comment by manuelcortez** [comment]
Hi,
I am aware of the Py2exe for Python 3 and that NVDA actively uses it. However when i have started the migration of several other projects to Python 3 Pyinstaller seemed good enough to package the project. TWBlue or any other project I work doesn't need any of the features NVDA requires as a software package, so it's easier/more confortable/stable to use PyInstaller than Py2exe at this time.
About translation services. That's a change I won't make to happen in TWBlue, unless someone would be willing to pay for the cost of the Google translate API. I know there are libraries out there that attempt to cheat in Google, but Google eventually discovers the trick, block user IP'S, or change the site layout so these libraries won't work at all. Yandex offers API access to their service (they offer up to 20 billion characters for free) and works relatively well,so there are no better and legal changes to do here unless there is a way to use the Google Translate API, which is a paid feature.

**Comment by ghost** [comment]
Is there an API limit?

**Comment by manuelcortez** [comment]
not as far as I know.

**Comment by ghost** [comment]
I have examined G.T modules that work very well with python.
They were making requests to the API.
So there was no such thing as html parse.

Y.T is of course a better choice if there is a request limit for IP.

**Comment by manuelcortez** [comment]
As I explained in the first  reply, google translate is paid (if you want to translate more than 500000 characters every month): https://cloud.google.com/translate/pricing. I know there are modules that works well with their API, but you have to put the money in google's hands in advance.
