### ISSUE TITLE
Support for virtual environments

### ISSUE THREAD

**Issue by Menelion** [manuelcortez/TWBlue#321]
It is a really good thing to use [virtual environments](https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/). The idea is that you have a folder with virtually separate Python, Pip and all needed packages. As TWBlue requires quite a lot of them nowadays, it would be nice to install all the stuff in a virtual environment.  
The thing is that when you create an environment with `py -m venv`, you have to provide the folder name for your environment. The folder is usually placed into the project folder (TWBlue in our case), so we need to add the environment name to our _.gitignore_ file.  
To do this, we need to decide about what this folder will be named. Different combinations like `_env`, `venv` and so on are possible, but at last the name should be unique to be included into _.gitignore_.

**Comment by SeanTolstoyevski** [comment]
In the official GitHub Python gitignore file, all of these possibilities are mentioned.

The other problem in my opinion: with windows depency files that take too long to download.

We should archive them with a tool like 7zip.

**Comment by Menelion** [comment]
@SeanTolstoyevski Apparently, TWBlue does not use Github's official .gitignore for Python since there is no mention of virtual environments in the file.

**Comment by JessicaTegner** [comment]
Hi.
another option for virtual environments would be to use a tool such as pipenv or poetry which creates and stores the virtual environment outside of the current working directory (ie the git repository in this case).
The only thing it stores is a file that holds dependency information (similar to the standard requirements.txt file).

**Comment by manuelcortez** [comment]
Hi there, I am aware of virtual environments. As a personal preference, I think it would be a good idea to use env as the folder name and to allow creating such folder inside the TWBlue repo. I am kinda against using third party tools because we already have something integrated in the default Python which can do the job with no problem. Adding more tools would be not needed IMO.
