### ISSUE TITLE
Where Does TWBlue Receive Twitter API Keys?

### ISSUE THREAD

**Issue by ghost** [manuelcortez/TWBlue#323]
Hello @manuelcortez,

I have good thoughts about TWBlue. But I want to walk a little on my own way. There are things I want to change in terms of interface and functionality.
Maybe if those changes are good, I'il open them up, maybe it'il be a shame.

I've been studying TWBlue's source code for a long time, but I couldn't find the **API keys**.

Where should I look?

**Comment by manuelcortez** [comment]
Hello, Api keys are DLL files which are present at src/keys/lib. You have examples to compile those yourself at mysc/keys.
