### ISSUE TITLE
No speach with latest snapshot.

### ISSUE THREAD

**Issue by tapper82** [manuelcortez/TWBlue#336]
Hi I just updated to latest snapshot and am not getting any speach from NVDA when the UI is hidden. NVDA 2020.1 windows 10 64 bit

**Comment by Mohamed00** [comment]
Try closing TWBlue and deleting the gen_py folder in your temp directory.

**Comment by tapper82** [comment]
@Mohamed00 You are a legend my friend! Thanks very much.
