### ISSUE TITLE
Replace Twython for Tweepy

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#337]
With the [upcoming changes announced by Twitter](https://blog.twitter.com/developer/en_us/topics/tools/2020/introducing_new_twitter_api.html) regarding their new hiteration of the API, I have researched about possible ways we can overcome this situation at TWBlue. As we have seen during the small change regarding direct messages, it seems Twython is not that actively mantained and supported as we found it to be in the past.

I have found [Tweepy,](https://github.com/tweepy/tweepy) a library that we have explored before but have not seen in a while, has a great and supporting community, and is actively developed. They have a few implementations such as cursored searches that we have had to do in our end with twython, for example. They also have support for the new Twitter's Streaming API, which might be useful for our interests.

But the most important reason that led me to bring it to here is that apparently they are going to support the latest API version. There is [this issue](https://github.com/tweepy/tweepy/issues/1345) with some kind of conversations regarding it and it looks promising, given the size of the community around Tweepy.

So I think we should switch to Tweepy and when Twitter finally give us access to their Labs site (access requested btw), we will have something to play with and a more stable and updated library.

thoughts?

**Comment by trodick** [comment]
@manuelcortez Sounds like a good idea to me. Tweepy has been around for a long time, at least ten years.

**Comment by manuelcortez** [comment]
Closed via #347
