### ISSUE TITLE
Generate snapshots automatically on every commit to the repo

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#338]
I have done other projects (namely Socializer and recently i have started in MusicDL with the same update approach) where all commits generally trigger generation of a distributable version of the application. It is supposed to be used as nightly builds or alpha versions, even more unstable than what we have at TWBlue as snapshots, and the idea behind that development cycle is that all interested people might give it a try and if things break, they send me a report. I think we might start doing about the same for snapshots here too. Basically the updates for snapshots might work like that:

1. Every new commit made in the TWBlue's source code will trigger a build in our continuous integration system.
2. During the build process, there is a script that adds the commit Id to the last line of the application.py file. So it looks like:  
update_next_version = "03286a44"
3. The version is generated in all variants (zipfile, installer) and uploaded via FTP to the project's directory along with the update file (the json where the commit ID of the built version is used as the current_version variable).
4. The User's snapshots will point to the update file, and will compare whether the value of their local update_next_version is different than the update file's current_version. If these IDS are not the same, the update process is triggered.
5. Obviously, there are commits that will not trigger a build (such as small updates to documentation or read me, etc).

This would allow us to develop faster and easier while authomating everything related to update's deployment to the CI architecture. The only disadvantage is that people would need to redownload the entire package every time an update gets released.

Thoughts?

**Comment by tapper82** [comment]
Yes I am OK with this.

**Comment by tapper82** [comment]
How do I get a snapshot of MusicDL?

**Comment by JessicaTegner** [comment]
I agree, I would say however, that needing to download each time a new snapshot gets build is kinda irritating and defeats the purpose of those kind of updates anyway.

**Comment by SeanTolstoyevski** [comment]
Can we separate it into beta, alpha and rc?

I don't know how we can do this, but existing CI apps may have support.
