### ISSUE TITLE
Image alt text isn't read/shown.

### ISSUE THREAD

**Issue by rkingett** [manuelcortez/TWBlue#340]
I hope this will become possible in Twitters new API, but will the free version of the API allow TW Blue to fetch the alt text of uploaded images and display them?

**Comment by Mohamed00** [comment]
Descriptions are supported. Unfortunately there's no shortcut for 
viewing them, so you have to view the tweet with alt+win+v to see them.

**Comment by rkingett** [comment]
Gotcha! Would it be possible to display the alt text in the buffer? Much like Long Tweets is?

**Comment by rkingett** [comment]
Perhaps in the next version, alt text could be displayed in the buffer? Closing this for now.
