### ISSUE TITLE
Stop adding http: // in front of all strings considered as links

### ISSUE THREAD

**Issue by CoBC** [manuelcortez/TWBlue#341]
Currently, when TWBlue considere a string like a link, he add http:// before this.
Unfortunately, some strings aren't links, and some links no requires http://, in some cases this addition can make problems. My suggest is to stop to do this.

**Comment by Mohamed00** [comment]
Twitter is doing this, not TWBlue. Any time Twitter sees something that 
looks like a link, it is automatically converted to a URL, even in the 
official apps.

**Comment by manuelcortez** [comment]
closing this as this issue is not exactly related to TWBlue itself.
