### ISSUE TITLE
No output for JAWS

### ISSUE THREAD

**Issue by cankirca** [manuelcortez/TWBlue#343]
Hello,

Using TWBlue more than a week and it worked well. But a new problem happend. Now when I run the app, JAWS not providing speech output with invisible keystrokes. I can hear sound notification with top and bottom edge, but JAWS not reading anything.
I've redownloaded the app and reauthorised it, but there is no solution.
BTW: GUI working as expected.

**Comment by Mohamed00** [comment]
Go into the run dialog by pressing windows+r, then type %tmp% and press 
enter. In the folder that appears, there should be a folder name gen_py. 
Delete that folder while TWBlue is closed and it should work the next 
time you start it.

**Comment by manuelcortez** [comment]
Fixed in #369
