### ISSUE TITLE
When playing audio files, the end of the file does not play.

### ISSUE THREAD

**Issue by KevanGP** [manuelcortez/TWBlue#344]
Hello,
I noticed a bug, when playing MP3 audio files, the last second or so of the file is chopped off and does not play when using TWBlue.

**Comment by KevanGP** [comment]
I was just able to reproduce this with a WAV file, too. I imagine it happens with other file types.

**Comment by manuelcortez** [comment]
Hi,
Are you testing with the last snapshot version or did you use a stable version to see those results? I am unable to reproduce the issue here.

**Comment by manuelcortez** [comment]
closing as we did not have more information for a while.
