### ISSUE TITLE
Many Countries aren't listed in the locations for trending topics like Iraq, Morocco,  palestine and Tunisia 

### ISSUE THREAD

**Issue by Ramon-Salazar** [manuelcortez/TWBlue#345]
Many of those locations aren't listed in the creation of trending topics, also many countries aren't listed.

**Comment by manuelcortez** [comment]
Hi,
Unfortunately, we cannot do anything regarding trending topic locations. This information is provided directly from Twitter. In case you want to read more, you can see the [Public API method](https://developer.twitter.com/en/docs/twitter-api/v1/trends/locations-with-trending-topics/api-reference/get-trends-available) from Twitter.
