### ISSUE TITLE
Rate limit gets quickly exceeded when updating buffers

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#354]
In the Tweepy version of TWBlue, when updating some buffers, such as followers or friends, manually using ctrl+alt+shift+u, the rate limit is immediatly exceeded.

**Comment by manuelcortez** [comment]
How many calls you have to perform to the update function before it gets limited?

**Comment by Mohamed00** [comment]
It happens even if I update a buffer once, and with TWBlue closed down 
for some time, to make sure I'm not hitting limits.

**Comment by manuelcortez** [comment]
How many items per API call you have set in the config? I am unable to reproduce it properly.

**Comment by Mohamed00** [comment]
I have it set to 200 items per buffer, with one API call.
