### ISSUE TITLE
can we get the retweets buffer back?

### ISSUE THREAD

**Issue by NathanTech7713** [manuelcortez/TWBlue#360]
The subject pretty much sums this up.
I realise twitter may have dropped support for this, but surely something could be thrown together with something like:
if(tweet.find("RT @"+username)):
  add to retweets buffer

Thanks in advance.

**Comment by manuelcortez** [comment]
Hi,
What would be the purpose of this buffer? I mean, would it show retweets of your own tweets or is it something different?

**Comment by NathanTech7713** [comment]
Exactly that. I like to see who has retweeted and if they did, what they said :).

While on this topic, could we also have an events buffer back, I realise twitter dropped this, but something simple like:
events: 1. bob followed you. 2. you followed jimmy. 3. new dm from bob. 4. bob liked your tweet.
It gets difficult to remember all of the sounds sometimes.

**Comment by manuelcortez** [comment]
We should study this when API v2 would be implemented. Though the problem with this approach would be to get all retweeted and quoted tweets. It would consume 2 API calls every time the buffer gets updated (quoted tweets are fetched via a search, while retweeted tweets have their on API call). I guess we can trick a normal search to fetch both retweets and quoted tweets, but we'd have to research more about this.

**Comment by trypsynth** [comment]
@manuelcortez, this appears to actually be possible, even with API V1. Spring did it on iOS. It's probably easier to get them in realtime with V2 though, like Spring did in V3.
