### ISSUE TITLE
Move to Gitlab

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#362]
Over the past year I have been using Gitlab more than github for basically all my other projects except TWBlue. Despite the possibility of using both sites together, which I currently do, the subject of this issue is to migrate the main repository used for adding issues and accepting code from github to gitlab. In particular, I am quite interested in [gitlab's service desk,](https://docs.gitlab.com/ee/user/project/service_desk.html) And [Gitlab Windows Runners](https://about.gitlab.com/blog/2020/01/21/windows-shared-runner-beta/) which would allow us to build TWBlue versions and receive user feedback (if we integrate service desk in TWBlue, for example) in the same platform. I even would think in using github for pull requests and gitlab for issues, as we can manage both repositories alltogether.
@jmdaweb, this would involve you to move the windows dependencies repository to gitlab, just to have everything in the same site.
What do you think?

**Comment by beqabeqa473** [comment]
it is possible to use github actions for building/testing stuff.

On 1/27/21, Manuel Cortéz <notifications@github.com> wrote:
> Over the past year I have been using Gitlab more than github for basically
> all my other projects except TWBlue. Despite the possibility of using both
> sites together, which I currently do, the subject of this issue is to
> migrate the main repository used for adding issues and accepting code from
> github to gitlab. In particular, I am quite interested in [gitlab's service
> desk,](https://docs.gitlab.com/ee/user/project/service_desk.html) And
> [Gitlab Windows
> Runners](https://about.gitlab.com/blog/2020/01/21/windows-shared-runner-beta/)
> which would allow us to build TWBlue versions and receive user feedback (if
> we integrate service desk in TWBlue, for example) in the same platform. I
> even would think in using github for pull requests and gitlab for issues, as
> we can manage both repositories alltogether.
> @jmdaweb, this would involve you to move the windows dependencies repository
> to gitlab, just to have everything in the same site.
> What do you think?
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/TWBlue/issues/362


-- 
with best regards Beqa Gozalishvili
Tell: +995593454005
Email: beqaprogger@gmail.com
Web: https://gozaltech.org
Skype: beqabeqa473
Telegram: https://t.me/gozaltech
facebook: https://facebook.com/gozaltech
twitter: https://twitter.com/beqabeqa473
Instagram: https://instagram.com/beqa.gozalishvili

**Comment by manuelcortez** [comment]
Yeah but still need to find a replacement to service desk, plus I have already running some gitlab CI pipelines with the same kind of build process needed to Build TWBlue.
