### ISSUE TITLE
Certain keystrokes don't work on TWBlue

### ISSUE THREAD

**Issue by coolbutpsycho** [manuelcortez/TWBlue#363]
Hello,
Using the latest snapshot of TWBlue on a Windows 10 64 bits, I tried to assign ALT+Win+. as a keystroke for using the "Search" option. Not only twblue doesn't recognize the assigned keys but also it's happening when I try editing other keystrokes.
Could it be fixed, please?
P.S.: Sorry if there's something wrong with this issue, it's my first attempt on doing something like that.

**Comment by manuelcortez** [comment]
Hi,

It was a nice issue reported, don't worry!

Unfortunately it seems this keystroke has been taken previously by Windows. Currently, TWBlue cannot assign keystrokes already used by other applications, including the operating system itself. You can see the [windows keystrokes here](https://support.microsoft.com/help/12445) and make sure you don't assign a keystroke which is already taken by the operating system.

**Comment by thgcode** [comment]
I don't know if this will work, but Maybe there's a way to fix it by creating a keyboard hook in TWBlue. I don't know if you already saw this, but what you think? See https://stackoverflow.com/questions/19356830/how-can-i-create-a-global-hotkey-combination-that-includes-the-windows-key
