### ISSUE TITLE
Load database of autocomplete users from Twitter API instead of taking objects from buffers

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#368]
Admittedly, for some (many?) people, loading the database of autocomplete users is kind of tricky, especially because in order to be successful, you have to load your friends and followers buffers completely. I think we might remove this requirement and make TWBlue to load everything in the first sync by using the endpoints [followers/ids,](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids) [friends/ids,](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids) and [users/lookup.](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup) Those endpoints are less limited (at about 900 calls per 15 minute window) and you can retrieve up to 5000 user IDS per API call to friends/ids and followers/ids, and 100 user objects in every call to users/lookup. So, in short we wouldn't spend calls to populating the buffers if we can make TWBlue to use those endpoints and retrieve the user IDS for friends and followers, and then converting those user IDS in real user objects via users/lookup.
This might make everything easier for people. They just would need to enable the feature and do the initial import. TWBlue then would keep importing new data as we have been doing so far, by taking the most recent added objects in buffers.

**Comment by rkingett** [comment]
I hope this can be done.
