### ISSUE TITLE
How top delete searches?

### ISSUE THREAD

**Issue by ChrisLewisW4** [manuelcortez/TWBlue#371]
I've created a lot of searches that I no longer need. How do I remove them from the search list?

**Comment by manuelcortez** [comment]
You remove them like any other buffer.

* In the graphical user interface, press alt to go to the menu bar, from there look for the buffer menu with the right arrow key, and after that press down until you hear remove buffer. You need to be focused in the search before you do this of course.
* For the invisible interface you need to press the key associated to the action of removing a buffer. You can look in the keymap editor for such keystroke. This is in the application menu, also in the menu bar on the invisible interface.

**Comment by ChrisLewisW4** [comment]
Brilliant, thanks Manuel.





*Chris Lewis *

+44 7824 360 747

@chr1slew1s

***@***.***

www.telcodebate.com

www.lewisinsight.com

[image: lewisinsight_Email_Sign]



*From:* Manuel Cortéz ***@***.***>
*Sent:* 09 March 2021 22:32
*To:* manuelcortez/TWBlue ***@***.***>
*Cc:* ChrisLewisW4 ***@***.***>; Author <
***@***.***>
*Subject:* Re: [manuelcortez/TWBlue] How top delete searches? (#371)



You remove them like any other buffer.

   - In the graphical user interface, press alt to go to the menu bar, from
   there look for the buffer menu with the right arrow key, and after that
   press down until you hear remove buffer. You need to be focused in the
   search before you do this of course.
   - For the invisible interface you need to press the key associated to
   the action of removing a buffer. You can look in the keymap editor for such
   keystroke. This is in the application menu, also in the menu bar on the
   invisible interface.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/manuelcortez/TWBlue/issues/371#issuecomment-794544587>,
or unsubscribe
