### ISSUE TITLE
TWBlue and OCR with tweets that have no texts

### ISSUE THREAD

**Issue by coolbutpsycho** [manuelcortez/TWBlue#375]
Hello,
Not sure if this is a known issue so thought I should report.
It looks like TWBlue's OCR doesn't work with tweets that havve no texts, that is, tweets that are only images. I try OCR-ing them and nothing happens. No delays but no results either.
I'm running TWBlue's last snapshot on a Windows 10 64 bits machine.
Thanks for reading.

**Comment by trypsynth** [comment]
OCR is only meant to get the text from images. It's not an image describer.
