### ISSUE TITLE
Error in Galician Arrow locale

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#376]
It seems there are certain fields in the timeframes defined for the Galician arrow locale that are not present in our implementation. This makes TWBlue to fail completely if language is set to Galician. I have disabled that locale in one of my last commits, but it might be useful to update our locale so it will support the Arrow specifications again.
@jmdaweb perhaps you can take a look?

**Comment by jmdaweb** [comment]
CC: @ivnc @quetzatl

**Comment by ivnc** [comment]
Arrow has already been problematic in the last stable release with Galician.
don't know, based on the provided details, what should it be done to fix this, but anyway wouldn't represent a great difference from the current situation. At least on my TWBlue installation relative dates are already read in English, although the application's language is set to Galician.

Regards.

**Comment by manuelcortez** [comment]
Hi,
@ivnc Basically you'd have to send a pull request by modifying the definition for the GalicianLocale we have at fixes/fix_arrow.py. There are certain missing fields in the class that makes arrow to fail when attempts to translate a message to Galician. You can see any arrow locale class at [this file](https://raw.githubusercontent.com/arrow-py/arrow/master/arrow/locales.py)(I have put the "raw" version of the file cause GitHub's interface takes ages to load the file). Copy any class (for example the Spanish one) and just translate the messages into Galician and that should be enough to be merged.
