### ISSUE TITLE
Return to the previous behavior in playing audio and opening URL

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#39]
There is no reason for detecting if TWBlue should try to play an audio or simply opening the URL when the user presses enter. We created the control+win+alt+enter to avoid this **unnecessary** check before doing an action. There are users (I, for example) who want to open the URL for downloading the audio and it does not allow to do this. Furthermore, this will take more time than the previous approach because sound_lib needs to try to load the URL and play it and if it fails, it will be opened by the web browser, so you are doing both proceses when the users may want only play or open the URL.

**Comment by codeofdusk** [comment]
Nope. Control+win+enter does the check, Ctrl+alt+win+enter bypasses the check and opens straight in the browser.

**Comment by codeofdusk** [comment]
I can rewrite interact so that the behavior can be toggled on/off, but as with all new features, let’s leave it enabled by default for wider testing, and add it to the Google form to determine what the default should be in the next release.

**Comment by codeofdusk** [comment]
Also, it doesn’t take that much more time. On a reasonably fast connection, it only takes about two or three seconds to check in most cases.

Bill

**Comment by manuelcortez** [comment]
This is not a feature, because it duplicates the functionality of the control+win+alt+enter keystroke, and (as I mentioned in the first comment) if the users wants the URL for downloading your algorithm will not allow this. Also you have mentioned that "in a reasonably fast connection..." but TWBlue is not a client "for fast connections only", some users have slow internet connections; internet in my work is not a very fast internet connection, and It takes 5 or 8 seconds to determine if the URL will be played or opened, and I don't want to wait 8 seconds for knowing if it will open the browser or try to play it.

**Comment by codeofdusk** [comment]
CTRL+win+alt+enter will always open the URL in the browser. But I’ll make it a toggle for users who don’t like the new behavior and for those on slow internet.

Again, this needs to be added to the Google form.

**Comment by manuelcortez** [comment]
In my source code (updated about an hour ago), ctrl+alt+win+enter tries to play the audio and raises a traceback because log is not a callable object.

**Comment by codeofdusk** [comment]
That’s a bug, I’ll look at it.

Bill

**Comment by codeofdusk** [comment]
Delete your session.conf and try again. See #40

**Comment by codeofdusk** [comment]
Do you still have issues with it on this revision?

**Comment by jmdaweb** [comment]
Hi Bill.
I understand your point of view, but that feature, even being optional, results in a worse program usability. There is a lot of people with very slow connections in many countries and an user can get frustrated if there is a delay between 3 and 8 seconds while navigating through the timeline.
Despite you have made very good contributions and you have great ideas, Manuel an I have decided to go back to the pull requests system with you, so we can decide which changes we will accept.
