### ISSUE TITLE
disappearing home timeline with an error message

### ISSUE THREAD

**Issue by fawazar94** [manuelcortez/TWBlue#398]
Hello, 
Yesterday happened something quite strange while reading the home time line, and surprisingly, it happened twice. 
I am using the latest snapshot. 
so, I am not certain how to reproduce it or how it had happened at the first place; nonetheless, the error message was as follows: 
"You have been blocked from viewing  someone's content. In order to avoid conflicts with the full session, TWBlue will remove the affected timeline."
when I clicked on Ok, it destroyed the home timeline. 
when I launched it again, it happened once more. 
note that the home timeline disappeared from the both interface.
thanks.

**Comment by CoBC** [comment]
I've saw the same issue with "mention" timeline, also with latest snapshot

**Comment by trypsynth** [comment]
Yup, I've had this issue too.

**Comment by chigkim** [comment]
I can also confirmed this. It removed my list as well as sent tweets. :(

**Comment by manuelcortez** [comment]
Closing as this should be fixed after we moved to Tweepy 4 and implemented a better exception handling there. Feel free to reopen if this still happens in latest snapshots,  though.
