### ISSUE TITLE
The player not closing automatically end of a clip

### ISSUE THREAD

**Issue by fawazar94** [manuelcortez/TWBlue#399]
Hello, 
The player is not closing automatically if the clip has been played from the TWBlue itself with Shift+Win+Alt+enter. 
furthermore, I can't close it with alt+f4 too. the only method I found to close it is to play the clip again and stop it using the same shortcut. 
I remember this issue wasn't there in the first snapshot where the feature was added. 
thanks.

**Comment by trypsynth** [comment]
CC @manuelcortez
