### ISSUE TITLE
can't link my Dropbox account to Twblue 

### ISSUE THREAD

**Issue by afiksof123** [manuelcortez/TWBlue#4]
hello. i have the latest version of the application. when i trying to link my dropbox account to the application, and paste the code, i get an error. 
why? how can i resolve the problem?

**Comment by codeofdusk** [comment]
Hello,
Could you please provide more information about the error?
When you say "latest version", do you mean latest version of the master (stable) branch, or the latest version of the next-gen branch? Are you running from source or a snapshot?

**Comment by afiksof123** [comment]
The latest version, I downloaded the installer from the website

**Comment by codeofdusk** [comment]
It works for me, I’m on the head of the next-gen branch.

Download the latest snapshot of next-gen from here. Does it work?

http://twblue.es/pubs/twblue_snapshot.zip

Thanks,

Bill.

**Comment by afiksof123** [comment]
The snapp shot is accesseble?

**Comment by codeofdusk** [comment]
If you mean to screen readers, of course. We're all blind developers and the client was written from the ground up for screen reader support.

**Comment by afiksof123** [comment]
So, I'll try it

**Comment by codeofdusk** [comment]
Thank you. If it works, please let me know so I can close this issue. If it doesn't, please include more information about exactly which error you're getting.

**Comment by afiksof123** [comment]
Ok

**Comment by afiksof123** [comment]
Hi bill.

No, the process of link the dropbox to the tw blue, not work.

**Comment by codeofdusk** [comment]
What does it do when you try?

Bill

**Comment by afiksof123** [comment]
I pasted the code, and than enter. And after than, I got a error message.

**Comment by afiksof123** [comment]
Can you give me direct link for the latest version of twblue?
