### ISSUE TITLE
Consider switching to GitHub releases?

### ISSUE THREAD

**Issue by trypsynth** [manuelcortez/TWBlue#400]
I know you used to use GitHub releases (the latest was 0.84). Might you consider doing this again? That's what I did for Quinter, then on twblue.es, just
```html
<a href="https://github.com/ManuelCortez/TWBlue/releases/latest">Click here to download!</a>
```
This way:
* You don't have to hardcode links.
* It makes checking for updates easier, just:
```python
try:
	latest = json.loads(requests.get("https://api.github.com/repos/ManuelCortez/TWBlue/releases/latest", {"accept": "application/vnd.github.v3+json"}).content.decode())
	if version < latest["tag_name"]:
# Ask the user if they want to download here. If you want a summary of release notes, it's latest["body"]
		if answer_is_yes:
			for i in latest['assets']:
				if "TWBlue.zip" in i['name'].lower() and platform.system()=="Windows":
					threading.Thread(target=download_update,args=[i['browser_download_url'],],daemon=True).start()
					return
# Other error handling.
```
Thoughts?

**Comment by manuelcortez** [comment]
I guess it would be a good idea, but I'd better use gitlab Releases to do the same. We already build and upload everything from the gitlab Ci windows runner, so it would be quite easy to integrate that workflow with links from there and checking updates via commit hashes as opposed to version numbers.

**Comment by trypsynth** [comment]
Yeah, sounds good to me.
