### ISSUE TITLE
Sharing a Tweet with Another User

### ISSUE THREAD

**Issue by chigkim** [manuelcortez/TWBlue#406]
Can we have the feature where you can forward a tweet with a specific user instead of retweet?

**Comment by manuelcortez** [comment]
Sadly this is not a feature directly supported by Twitter. As such, we are unable to provide a functionality relying in their API. Although you might get what you would like to do by adding a quote to a tweet and mentionning the @username in the quote. This way you wouldn't need to do anything new to share tweets, just add quotes and mention people you want to share the tweet with in the quote.
