### ISSUE TITLE
Traceback when launching newest TWBlue

### ISSUE THREAD

**Issue by ndarilek** [manuelcortez/TWBlue#415]
Hello,

Just upgraded to 2021.10.27. Installation worked fine, but launching gives me this error:

Traceback (most recent call last):
  File "__startup__.py", line 113, in run
  File "Console.py", line 15, in run
  File "main.py", line 3, in <module>
  File "win32com\__init__.py", line 5, in <module>
ImportError: DLL load failed while importing win32api: The specified module could not be found.

Thanks!

**Comment by Neurrone** [comment]
Got the same problem too. Is there a way for me to download a previous version to revert to a working build?

**Comment by manuelcortez** [comment]
It should be fixed in Version 2021.10.30. You might want to remove files from version 2021.10.27 and reinstall.

**Comment by Neurrone** [comment]
@manuelcortez What's the download link for 2021.10.30? On the downloads page, it only has 2021.10.27

**Comment by manuelcortez** [comment]
Use that link. It will get the latest available version. The version listed in the site will be updated soon.

**Comment by Neurrone** [comment]
Which link are you referring to? I'm using the link on https://twblue.es/downloads/ which leads to https://twblue.es/pubs/twblue_setup.exe

I just tried redownloading that file and reinstalling but see the same error. Are you referring to a different link?

**Comment by Neurrone** [comment]
I uninstalled TwBlew and reinstalled it with the link from the site and it looks like I got the correct version.

However, nothing happens when I launch twblue.exe, previously there was a stack trace that appears but now, nothing seems to happen.

Are there any logs that I could look at to see what may be wrong?

**Comment by Neurrone** [comment]
Nvm, figured it out. Had to delete my config folder and everything's working again.

Thanks!

**Comment by manuelcortez** [comment]
You said you uninstalled the app and reinstalled, but did you delete the %appdata%\twblue folder when uninstalling? if not, please try to remove that folder and start the app again to see if that works.

**Comment by Neurrone** [comment]
Yup, deleting the config folder there fixed it.

**Comment by ObjectInSpace** [comment]
I just redownloaded from the link on the sight and got the same error, even after deleting configuration.

**Comment by manuelcortez** [comment]
@ObjectInSpace which windows version do you have, architecture and are you using portable or installer?

**Comment by ObjectInSpace** [comment]
WIn10X64, I used the installer and not the portable version.

**Comment by manuelcortez** [comment]
@ObjectInSpace can you check if the portable works for you, so we can get a better understanding about how those versions work for your system? Additionally, were you installing the latest version from scratch, right? I mean you removed your config from appdata and also uninstalled the previous versoin.

**Comment by ObjectInSpace** [comment]
Durp! I forgot to uninstall first. That+removing appdata got it working again! Thanks much.
