### ISSUE TITLE
the latest 32-bit version does not work on Windows 7

### ISSUE THREAD

**Issue by discapacidad5** [manuelcortez/TWBlue#416]
version 2021.10.27

It says that the dll is compatible with that version of windos

api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll

Apparently this one and I don't know which ones are 64bit and not 32bit

**Comment by manuelcortez** [comment]
should be fixed in Version 2021.10.30

**Comment by discapacidad5** [comment]
By the time that version is scheduled to be released, the latest version published on the page is 2021.10.27

**Comment by manuelcortez** [comment]
Use the same download link, it will always download the latest available version. The site will be updated soon.

**Comment by discapacidad5** [comment]
The problem is that I cannot install the version of the page because it does not work in 32 bits how can I download that version so that it is updated is impossible If I can't install it, I can't update it
