### ISSUE TITLE
bug: unable to clear the direct messages buffer

### ISSUE THREAD

**Issue by jeremyp3** [manuelcortez/TWBlue#418]
I am using the latest version of TWBlue (2021.10.30) and find that it is impossible to clear the direct messages buffer. when using the cache, it is useful to be able to empty a buffer to have only the most recent elements

Please fix this bug

Jeremyp3

**Comment by manuelcortez** [comment]
Could you shouw us your errors.log file so we can check which kind of traceback does it raise?

**Comment by manuelcortez** [comment]
Nevermind, figured it out.
