### ISSUE TITLE
Missing translations in latest versions

### ISSUE THREAD

**Issue by CoBC** [manuelcortez/TWBlue#419]
Hi,
I can see that my two latest PR for french translation was merged, but the translation is not up to date in TWBlue 2021.10.30.
What can explain this?
Thanks.

**Comment by manuelcortez** [comment]
Hi,
probably it is related to the fact that currently TWBlue does not generate or update the translation compiled MO files. Will add this to the CI so it will update all catalogs prior every new release.

**Comment by CoBC** [comment]
Translations are now correctly updated in latest versions. Not anymore an issue.
