### ISSUE TITLE
missing "Find a string in the currently focused buffer" in keystroke editor

### ISSUE THREAD

**Issue by jeremyp3** [manuelcortez/TWBlue#420]
Hello,

in the old version of TWBlue that I was using (still under python2), I could define a keyboard shortcut for the option "Find a string in the currently focused buffer"

since python3 i can't set this keyboard shortcut anymore.

is it an oversight?

I find this keyboard shortcut handy so as not to have to display the graphical interface to be able to perform this action

thanks ! 

Jeremyp3

**Comment by manuelcortez** [comment]
Show us your logs please. without them we are unable to fix anything as we need to see what has failed in your specific issue.

**Comment by jeremyp3** [comment]
I cannot create the shortcut since it does not exist in the "keystroke editor" dialog

the hitem should be added, if possible.

it is not a mistake in attribution

thanks,

Jeremyp3

**Comment by jeremyp3** [comment]
hello,

after more than 6 months without activity, I allow myself to revive this issue.


when TWBlue is in hidden interface mode, you can't open the dialog box to search for a string in a buffer, because you can't assign shortcuts to this function in the shortcut editor. the item does not exist in the list

thanks !

Jeremyp3
