### ISSUE TITLE
Cannot post tweets

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#436]
Hi, I noticed that as of the latest commit, it's not possible to post tweets. When attempting to post one, the following error is displayed.
10/11/2021 19:41:29 mysc.thread_utils ERROR: Thread 7400 with function <bound method Session.send_tweet of <sessions.twitter.session.Session object at 0x0000016E3E291848>>, args of ({'text': 'test', 'attachments': [], 'poll_options': None, 'poll_period': None},), and kwargs of {} failed to run.
Traceback (most recent call last):
  File "C:\twblue\src\mysc\thread_utils.py", line 12, in new_func
    func(*a, **k)
  File "C:\twblue\src\sessions\twitter\session.py", line 624, in send_tweet
    item = self.api_call_v2(call_name="create_tweet", text=obj["text"], _sound="tweet_send.ogg",  in_reply_to_tweet_id=in_reply_to_status_id, poll_duration_minutes=obj["poll_period"], poll_options=obj["poll_options"])
  File "C:\twblue\src\sessions\twitter\session.py", line 228, in api_call_v2
    val = getattr(self.twitter_v2, call_name)(*args, **kwargs)
AttributeError: 'Client' object has no attribute 'create_tweet'

**Comment by manuelcortez** [comment]
Update to latest Tweepy 4.3.0. That should be enough.

**Comment by Mohamed00** [comment]
That worked, thanks.
