### ISSUE TITLE
Image descriptions sometimes stop appearing in the invisible interface

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#449]
I'm not sure of exact steps to reproduce this issue yet. It seems that after running TWBlue for a while, image descriptions will stop appearing in the invisible interface, even though the template includes them. Clearing the buffer and updating it again seems to fix the issue, though.

**Comment by manuelcortez** [comment]
I think Twitter does retrieve descriptions for images only via the Rest API. I can't make it in the Streaming endpoints. Even the Rest API is basically undocumented. I'm not very sure what to do from here.
