### ISSUE TITLE
Repository transfer

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#451]
As I have explained in [this blog post,](https://manuelcortez.net/blog/changes-in-projects-for-next-year/) I'll be creating a Software company to be able to receive some benefits from local initiatives here in Mexico. This issue is just to discuss the fact that after this month, TWBlue's main repository will be transferred to [MCV Software in github.](https://github.com/mcv-software) Everything else should remain the same. Github adds a redirection from the current repository namespace to the new one, although it would be advisable to change the git remote address to the new one, once the repository will be transferred.

**Comment by rkingett** [comment]
Very happy you will be able to get grants and otherwise!

**Comment by trypsynth** [comment]
Is this done? It seems to be.

**Comment by manuelcortez** [comment]
Yes, it is already done. Sorry, forgot to close the issue.
