### ISSUE TITLE
In the invisible interface, the string  for quoted tweets is no longer translatable

### ISSUE THREAD

**Issue by nidza07** [manuelcortez/TWBlue#463]
Hello,
with the new templates system, it appears that we lost the translation for a quoted tweet.
Switch to a language different from English, tested with Serbian and French.
Focus on a quoted tweet using the invisible interface.
The tweet is spoken, and after that the English text "Quote from @%s"
%s being replaced with the username of course.
Previously, the part explaining that it is a quoted tweet was translated into whatever language you were using, and this remains the case if you are using the GUI.

Thanks.

**Comment by CoBC** [comment]
Fixed by #503

**Comment by nidza07** [comment]
thank you @CoBC
