### ISSUE TITLE
Double UI controls in main window.

### ISSUE THREAD

**Issue by trypsynth** [manuelcortez/TWBlue#475]
When showing the window with ctrl+win+w, I get my tweets list, the buttons, another empty list, and the same buttons, plus the tree view. Even in the DM view, I get the DM list, two buttons, then an empty list, and all 4 of the standard tweet buttons.

**Comment by manuelcortez** [comment]
i there,
do you have anything in logs? Have never seen it.

**Comment by trypsynth** [comment]
Nope, nothing in logs. I can provide an audio recording, if you like.

**Comment by trypsynth** [comment]
for some reason, this no longer seems to be an issue with the Mastodon session.
