### ISSUE TITLE
GUI and Global Keystrokes are not synchronised

### ISSUE THREAD

**Issue by brianhartgen** [manuelcortez/TWBlue#49]
Steps to reproduce:
1. Navigate the home buffer using the GUI and the Up and Down Arrow keys.
2. Press control windows right arrow to move to the Mentions buffer.
3. Try using the up and down arrow keys.
Expectation: the list should reflect the buffer selected, I.E., Mentions.
Result: The list contains those tweets you were previously viewing, Home.

**Comment by manuelcortez** [comment]
Hi, I can reproduce that bug, will be fixed for the next snapshot. Thanks alot for your report!

**Comment by codeofdusk** [comment]
Which version of the client are you using? Are you using a prebuilt version, or are you running from source? What operating system are you using?

**Comment by codeofdusk** [comment]
Never mind, I didn't see that Manuel got this already.
