### ISSUE TITLE
composing tweets and replys not working in Arabic interface

### ISSUE THREAD

**Issue by sulaiman-alqusaimi** [manuelcortez/TWBlue#492]
There is an old issue in this app in which Arab users who use the Arabic interface can not create a new nor reply to a tweet.
Previously, it was pocible to show the compose tweet dialog but the send button was not working.
Now, the compose dialog does not show up at all.
Working with the English interface of TWBlue and Arabic interface for windows does not reproduce the issue.

**Comment by manuelcortez** [comment]
Hi, could you reproduce the issue and paste here the contents of the log files?

**Comment by manuelcortez** [comment]
Closing as Twitter support is being Dropped in TWBlue after they have deleted our API access.
