### ISSUE TITLE
Problem translating using WebLate

### ISSUE THREAD

**Issue by CoBC** [manuelcortez/TWBlue#497]
Hi,
I can't translate TWBlue using WebLate anymore. WebLate alerts about an issue when retrieving last modification from repository, and translation is locked.
@manuelcortez can you have a look?
Thanks.

**Comment by manuelcortez** [comment]
Hi there, Sorry, I have done some changes to the infra where gitlab runs and it had some issues to connect to weblate. Now things seems to be fixed now. Will update the translation strings asap.
