### ISSUE TITLE
Twitter: filtering by language doesn't work

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#502]
### Steps to reproduce
1. Search for a term on Twitter, example: demucs
2. Set language for results to English
### Expected
Only English language results are displayed
### Actual
Results in several languages are displayed

**Comment by trypsynth** [comment]
@manuelcortez, given the extremely sad fait of the Twitter session, should we close this, as well as any other twitter issues?

**Comment by Mohamed00** [comment]
I'll think I'll close this one, since the Twitter session will be expiring tomorrow anyway.
