### ISSUE TITLE
Client runs and builds under 64-bit Python installations, but built distributions throw error on launch

### ISSUE THREAD

**Issue by codeofdusk** [manuelcortez/TWBlue#51]
When attempting to run a copy of TWBlue built with the 64-bit Python implementation, an error about libiconv.dll is displayed. Running from source under 64-bit works fine, as do 32-bit builds.

**Comment by manuelcortez** [comment]
Did you used the enchant package provided with the windows dependencies?

**Comment by codeofdusk** [comment]
Yes.

**Comment by manuelcortez** [comment]
Sorry, but I am able to create a distributable TWBlue using Python for 64 bits without problems. I think the problem is not in the files provided with TWBlue, so probably you may need to check (or copy) the missing library to work properly.
