### ISSUE TITLE
Mastodon: Incorrect character count calculation

### ISSUE THREAD

**Issue by riku22** [manuelcortez/TWBlue#511]
Hello.

Mastodon's calculation of the number of characters is incorrect.
Specifically, Mastodon treats multibyte characters (e.g., `あ`) and emojis (e.g., "`😊") as one character.
Currently, both are counted as two characters, similar to the Twitter specification.
URLs are counted as 23 characters as in Twitter.
If possible, I would appreciate it if you could fix this.

**Comment by manuelcortez** [comment]
Hi there, should be fixed already on commit https://github.com/MCV-Software/TWBlue/commit/63ae496c3945e1e816ed896bf3091441f5a20de6
