### ISSUE TITLE
Mastodon 1000+ connections 

### ISSUE THREAD

**Issue by azcoigreach** [manuelcortez/TWBlue#512]
On two different occasions now, including right now.  I have users on my Mastodon server, using TWBlue.  With 1000+ connections spamming my server.  It looks as if I am having a DDoS attack when it is actually a runaway TWBlue client.  The end-users do not seem to be aware this is happening.

**Comment by manuelcortez** [comment]
Hi, this should be already fixed with our last release. If you consider it's still happening, feel free to reopen the issue so we can further research on this.
