### ISSUE TITLE
A typo in the notifications buffer

### ISSUE THREAD

**Issue by MuhammadHassan0000** [manuelcortez/TWBlue#519]
The following typo has been detected in this notification
The appp's language is english by the way, and latest version
Collei :verified:; Collei :verified: has mentionned you: Collei :verified:, ,@mo2003 What instrument are you playing?,a day ago, ,Web  39 of 40
The typo is in mentionned
It should be mensioned I think.

**Comment by Arfs6** [comment]
Actually, I think it's mentioned. With one `n`.
