### ISSUE TITLE
Pressing on  report an error does not work

### ISSUE THREAD

**Issue by MuhammadHassan0000** [manuelcortez/TWBlue#520]
When i press on the Report an error in the help menu It does not do anything and takes me back to the home screen. I thought It should direct me to here.

**Comment by Arfs6** [comment]
I searched the source code but couldn't find where the report an error was implemented. I think the intention was to redirect the user to (this)[https://github.com/mcvsoftware/twblue/issues] issues page on github. I got the link from (application.py)[https://github.com/MCV-Software/TWBlue/blob/next-gen/src/application.py].
The ui element was added to mainFrame in (View.py)[https://github.com/mcV-Software/TWBlue/blob/next-gen/src/wxUI/view.py] but it wasn't connected to it's function in Controller.

**Comment by Arfs6** [comment]
Just realised, markdown doesn't work here. I have fixed the bug and created a pull request. Waiting for @manuelcortez to review the changes.

**Comment by Arfs6** [comment]
@manuelcortez I have solved this and created a pull request. Could you please check it out when you're busy?
