### ISSUE TITLE
Mastodon: editing some template items no longer works as of the latest commit

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#521]
### Steps to reproduce.
1. Replace $safe_text with just $text, for example.
### Expected.
The text of a post should be shown.
### Actual.
The content warning is still shown. This seems to not affect other fields such as $source, though.

**Comment by manuelcortez** [comment]
This is not a bug (at least intentionally). Tere's a setting, located in account settings, that allows you to set wether TWBlue should respect your preferences (as saved in your instance's website). This is enabled by default, which means that TWBlue will not display content warnings by default. I just realised this makes it harder to edit templates and make them work properly, so probably I'll make templates to not respect this setting so you would be able to hide/show content warnings automatically by editing templates as opposed to rely in 2 different settings (template editing and  reading preferences from instance).

**Comment by Mohamed00** [comment]
Oops, just realized I had that checked. Blame a lack of sleep. But yeah, that could work, or if read preferences from instance is checked, items such as that which are controlled by the instance could be hidden from the template editor.
