### ISSUE TITLE
No CONTRIBUTING.md

### ISSUE THREAD

**Issue by Arfs6** [manuelcortez/TWBlue#523]
I can't find a CONTRIBUTING.md file. Please what are the steps one needs to take if he/she wants to contribute to the project? tnx.

**Comment by ChrisDuffley** [comment]
@Arfs6: I belivee that most people contribute by sending in pull requests/issues like you just did here by forking the repo and submitting changes by your forked branch to the next-gen branch.
@manuelcortez: Can you clarify this?
Thanks!

**Comment by Arfs6** [comment]
Oh ok. Thanx.
