### ISSUE TITLE
Mastodon: cannot reply with one mention in Mentions buffer

### ISSUE THREAD

**Issue by jfayre** [manuelcortez/TWBlue#525]
If there is only one mention in the Mentions buffer on a Mastodon session, pressing Reply in the window does nothing. Also, mentions buffer in the invisible interface is showing no mentions. I'm attaching logs.
[twblue_logs.zip](https://github.com/MCV-Software/TWBlue/files/10831394/twblue_logs.zip)

**Comment by manuelcortez** [comment]
Should be fixed just now in [d01856f](https://github.com/MCV-Software/TWBlue/commit/d01856f)
