### ISSUE TITLE
Connection  closing  whily  sending tweets.

### ISSUE THREAD

**Issue by jonasmarques** [manuelcortez/TWBlue#527]
When creating a tweet and executing the send action the tweet is never sent and just returns an error.

I'll attach the log files for debugging, but it seems to me that something is closing or blocking the connection in urlib3
[logs.zip](https://github.com/MCV-Software/TWBlue/files/10949032/logs.zip)

**Comment by manuelcortez** [comment]
Closing as Twitter support is being Dropped in TWBlue after they have deleted our API access.
