### ISSUE TITLE
I have a problem with TWBlue for Twitter

### ISSUE THREAD

**Issue by discapacidad5** [manuelcortez/TWBlue#531]
I have a problem with TWBlue for Twitter. Since the day before yesterday, TWBlue stopped loading and says that I need to log in again because the token has expired. However, when I click on 'start new session,' the browser window does not open to allow me to log in. It just does nothing. With Mastodon, the browser opens, but I need it to work with Twitter. I have tried installing it on other computers and even the portable version, but the same thing happens.

**Comment by Mohamed00** [comment]
Twitter killed the app, sorry. Clients like TWBlue are officially 
violating the terms of service now, and all apps are likely to get 
killed over the next month or so.
