### ISSUE TITLE
Weblate: repository push error and merge error

### ISSUE THREAD

**Issue by riku22** [manuelcortez/TWBlue#534]
Hello.

I'm trying to update TWBlue's translation and noticed that I'm getting errors "Unable to push repository." and "Unable to merge repository."
Could you please fix it?

Ref: https://weblate.mcvsoftware.com/projects/twblue/twblue/#alerts

**Comment by riku22** [comment]
> Hello.
> 
> I'm trying to update TWBlue's translation and noticed that I'm getting errors "Unable to push repository." and "Unable to merge repository." Could you please fix it?

Ref: <https://weblate.mcvsoftware.com/projects/twblue/twblue/#alerts>

**Comment by manuelcortez** [comment]
Hi there, that should already be fixed on latest commit. Thanks!
