### ISSUE TITLE
timelines, more than one of the same user's timeline are able to be added this should be forbidden.

### ISSUE THREAD

**Issue by mhussaincov93** [manuelcortez/TWBlue#537]
1.
launch twblue.
2.
add someone's timeline to the list of timelines via  the view timelines feature.
3.
re add the same users timeline to the list of timelines.
what happens?
the timeline of the same user is addable more than once.
what should happen?
when you try to add another of the same timeline from the same user, you should add a message telling the user that a timeline is allready present.
latest version of twblue.
32 bit portable.
since 64 bit version does not work.

**Comment by Arfs6** [comment]
@manuelcortez I think this is fix already, so it should be closed.
