### ISSUE TITLE
Unable to view user profiles

### ISSUE THREAD

**Issue by KevanGP** [manuelcortez/TWBlue#554]
I can pull user timelines for Mastodon in TW Blue.
However the view user profile option in the UI is unavailable, and the keystroke in the invisible interface that used to do so for X doesn't seem to exist.
By user profile, I mean information such as a user's name, bio or followed/following count.
Can this please be re-added?

**Comment by Arfs6** [comment]
I have started working on the show user profile button. I will try and send the pull request later today. But the viewing users followers and following, I haven't even thought of that. Regardless, that won't be an issue.

**Comment by Arfs6** [comment]
A pull request have been opened to take care of this issue. link: https://github.com/MCV-Software/TWBlue/pull/555
And regarding viewing posts, followers and following, I knew it was possible. 
Go to the menu,
> users
> open timeline
> posts / followers / following
to open a buffer with the focused user's followers, posts or following.
A button might be added to the view user profile option to create the same buffers too.

**Comment by Arfs6** [comment]
@manuelcortez this issue needs to be closed since the pull request was merged.
