### ISSUE TITLE
Releases section is not up-to-date

### ISSUE THREAD

**Issue by Neustradamus** [manuelcortez/TWBlue#558]
Dear @MCV-Software team, @manuelcortez,

You can see here at right:
- https://github.com/MCV-Software/TWBlue
```
Releases 8
Version 0.84
Latest on Aug 4, 2016
+ 7 releases
```

Can you look because it is very very old:
- https://github.com/MCV-Software/TWBlue/releases

Can you add all build packages too?

Tags:
- https://github.com/MCV-Software/TWBlue/tags

Thanks in advance.

**Comment by manuelcortez** [comment]
Hi there, We will work in integrations with gitHub Releases, thanks for this report. Will keep it open until we can have this done.

**Comment by Neustradamus** [comment]
@manuelcortez: Can you remove all releases from GitHub, it shows an old project:
- https://github.com/MCV-Software/TWBlue/releases

**Comment by Arfs6** [comment]
@Neustradamus The releases section is now up to date. It has the latest version of TWBlue. Enjoy!
@manuelcortez This is ready for closing as well.
