### ISSUE TITLE
Create TW Blue official account on Mastodon

### ISSUE THREAD

**Issue by Arfs6** [manuelcortez/TWBlue#562]
Advantage: Reporting bugs, asking for help and following TW Blue update will be easier. Although the getting help part could be solved by improving the support for hashtags in TW Blue.
Disadvantage: Someone needs to maintain the account, post TW Blue related updates and reply to users.
What do you think?

**Comment by manuelcortez** [comment]
I have been thinking about this. Currently I use the account twblue@maaw.social (that domain was kind of a joke between my whife and myself so it does not make sense out of our context tbh). It's in the release announcements at https://mcvsoftware.com/category/news and it will be in our documentation too. But I might create an account in an instance for FOSS projects.

**Comment by Arfs6** [comment]
Oh ok. I didn't know an account existed already.
I don't see any problem with the domain you're using now. If you can maintain it, use I think it is okay.
