### ISSUE TITLE
Does TWBlue work with Twitter/X again?

### ISSUE THREAD

**Issue by chigkim** [manuelcortez/TWBlue#564]
Apparently Spring, another third party accessible client, mysteriously started working again with Twitter/X.

Has anyone checked if TWBlue works again too?

**Comment by Arfs6** [comment]
TW Blue has removed support for twitter in latest versions.
I don't think you can try it.

**Comment by Arfs6** [comment]
@manuelcortez I think this issue has been delt with, so it should be closed.
