### ISSUE TITLE
Delete interact function

### ISSUE THREAD

**Issue by manuelcortez** [manuelcortez/TWBlue#57]
The interact function should bedeleted. We will return to the "audio" function for playing audios. If you play an audio using the interact method, when you try to stop it, it will stop the audio then it will open an URL.

**Comment by codeofdusk** [comment]
You did it wrong! When you tried to revert some of my commits it broke…

Bill

**Comment by manuelcortez** [comment]
Yes, we will use the Control+Wi+enter key for playing audios only, so we
will return to the previous version.
