### ISSUE TITLE
Unable to boost a post by using the graphical  interface, if the option Ask confirmation before boosting a post is disabled

### ISSUE THREAD

**Issue by nikosdemetriou** [manuelcortez/TWBlue#582]
Hi.
From the account settings of twblue, if we disable the option Ask confirmation before boosting a post, it is impossible to boost something unless if we use the hotkey windows+alt+shift+R.
We cannot right click a post and choose boost, or to tab a few times to find the boost button.
Nothing happens if we try to boost from the graphical interface. Only by using the hot key.
Thanks

**Comment by Arfs6** [comment]
Hi.
This bug was fixed by @manuelcortez recently. Here is the commit url if you're interested; https://github.com/mcV-Software/TWBlue/commits/36420d6a5bdfb83e41c4ca5c523621de96456847

**Comment by jmdaweb** [comment]
Then, let's close it.
