### ISSUE TITLE
Mastodon: instance suffix is not added when viewing a user's timeline from the community timeline

### ISSUE THREAD

**Issue by Mohamed00** [manuelcortez/TWBlue#638]
### Steps to reproduce.
1. Create a new community timeline for an instance.
2. Load the timeline of a user on that instance.

### Expected.
The user's name should be suffixed with the instance name, for example username@mastodon.social.
#### Actual.
The user's name doesn't have the instance they're on added to it, which results in that user's timeline failing to load if they're not on the same instance as you.

**Comment by manuelcortez** [comment]
Should be fixed in commit 002d0a5
