### ISSUE TITLE
Twblue

### ISSUE THREAD

**Issue by ghost** [manuelcortez/TWBlue#64]
Hi, texsting your product. I installed it and tried to authorize it. The twitter page came up with an error, and now the program won't run. It will sstill install, but not load the authorize dialogue box.

**Comment by codeofdusk** [comment]
What was the error you got from the Twitter page?
Is there a TWBlue folder in your %appdata% (Type that into the run dialog)? If so, delete it and try again.

Bill

**Comment by ghost** [comment]
I'm not sure what the error was.

On 11/8/15, Bill Dengler notifications@github.com wrote:

> What was the error you got from the Twitter page?
> Is there a TWBlue folder in your %appdata% (Type that into the run dialog)?
> If so, delete it and try again.
> 
> Bill
> 
> > On Nov 8, 2015, at 16:52, novelistics notifications@github.com wrote:
> > 
> > Hi, texsting your product. I installed it and tried to authorize it. The
> > twitter page came up with an error, and now the program won't run. It will
> > sstill install, but not load the authorize dialogue box.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/manuelcortez/TWBlue/issues/64.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by ghost** [comment]
I've deleted the folder, now will try again.

On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:

> I'm not sure what the error was.
> 
> On 11/8/15, Bill Dengler notifications@github.com wrote:
> 
> > What was the error you got from the Twitter page?
> > Is there a TWBlue folder in your %appdata% (Type that into the run
> > dialog)?
> > If so, delete it and try again.
> > 
> > Bill
> > 
> > > On Nov 8, 2015, at 16:52, novelistics notifications@github.com wrote:
> > > 
> > > Hi, texsting your product. I installed it and tried to authorize it. The
> > > twitter page came up with an error, and now the program won't run. It
> > > will
> > > sstill install, but not load the authorize dialogue box.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/manuelcortez/TWBlue/issues/64.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580
> 
> ## 
> 
> Pen Name:
> Mellissa Green
> Twitter
> @abluegreenunivs
> 
> website
> 
> www.abluegreenuniverse.com

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by ghost** [comment]
Twitter error. Something is technically wrong.

Thanks for noticing—we're going to fix it up and have things back to
normal soon.

On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:

> I've deleted the folder, now will try again.
> 
> On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:
> 
> > I'm not sure what the error was.
> > 
> > On 11/8/15, Bill Dengler notifications@github.com wrote:
> > 
> > > What was the error you got from the Twitter page?
> > > Is there a TWBlue folder in your %appdata% (Type that into the run
> > > dialog)?
> > > If so, delete it and try again.
> > > 
> > > Bill
> > > 
> > > > On Nov 8, 2015, at 16:52, novelistics notifications@github.com wrote:
> > > > 
> > > > Hi, texsting your product. I installed it and tried to authorize it.
> > > > The
> > > > twitter page came up with an error, and now the program won't run. It
> > > > will
> > > > sstill install, but not load the authorize dialogue box.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/manuelcortez/TWBlue/issues/64.
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580
> > 
> > ## 
> > 
> > Pen Name:
> > Mellissa Green
> > Twitter
> > @abluegreenunivs
> > 
> > website
> > 
> > www.abluegreenuniverse.com
> 
> ## 
> 
> Pen Name:
> Mellissa Green
> Twitter
> @abluegreenunivs
> 
> website
> 
> www.abluegreenuniverse.com

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by ghost** [comment]
I'm in. Love the name, where did it come from? Blue is my favorite
color, check out my website, abluegreenuniverse.com

On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:

> Twitter error. Something is technically wrong.
> 
> Thanks for noticing—we're going to fix it up and have things back to
> normal soon.
> 
> On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:
> 
> > I've deleted the folder, now will try again.
> > 
> > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > wrote:
> > 
> > > I'm not sure what the error was.
> > > 
> > > On 11/8/15, Bill Dengler notifications@github.com wrote:
> > > 
> > > > What was the error you got from the Twitter page?
> > > > Is there a TWBlue folder in your %appdata% (Type that into the run
> > > > dialog)?
> > > > If so, delete it and try again.
> > > > 
> > > > Bill
> > > > 
> > > > > On Nov 8, 2015, at 16:52, novelistics notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > Hi, texsting your product. I installed it and tried to authorize it.
> > > > > The
> > > > > twitter page came up with an error, and now the program won't run. It
> > > > > will
> > > > > sstill install, but not load the authorize dialogue box.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/manuelcortez/TWBlue/issues/64.
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580
> > > 
> > > ## 
> > > 
> > > Pen Name:
> > > Mellissa Green
> > > Twitter
> > > @abluegreenunivs
> > > 
> > > website
> > > 
> > > www.abluegreenuniverse.com
> > 
> > ## 
> > 
> > Pen Name:
> > Mellissa Green
> > Twitter
> > @abluegreenunivs
> > 
> > website
> > 
> > www.abluegreenuniverse.com
> 
> ## 
> 
> Pen Name:
> Mellissa Green
> Twitter
> @abluegreenunivs
> 
> website
> 
> www.abluegreenuniverse.com

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by codeofdusk** [comment]
The client is for blind users.
I don’t know where the name originated from, I’m not the project author/maintainer but have collaborated with him on it.
@manuelcortez @jmdaweb creo que podéis cerrar esto ahora.

**Comment by ghost** [comment]
It's very nice.

On 11/8/15, Bill Dengler notifications@github.com wrote:

> The client is for blind users.
> I don’t know where the name originated from, I’m not the project
> author/maintainer but have collaborated with him on it.
> @manuelcortez @jmdaweb creo que podéis cerrar esto ahora.
> 
> > On Nov 8, 2015, at 22:38, novelistics notifications@github.com wrote:
> > 
> > I'm in. Love the name, where did it come from? Blue is my favorite
> > color, check out my website, abluegreenuniverse.com
> > 
> > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > wrote:
> > 
> > > Twitter error. Something is technically wrong.
> > > 
> > > Thanks for noticing—we're going to fix it up and have things back to
> > > normal soon.
> > > 
> > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > wrote:
> > > 
> > > > I've deleted the folder, now will try again.
> > > > 
> > > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > > wrote:
> > > > 
> > > > > I'm not sure what the error was.
> > > > > 
> > > > > On 11/8/15, Bill Dengler notifications@github.com wrote:
> > > > > 
> > > > > > What was the error you got from the Twitter page?
> > > > > > Is there a TWBlue folder in your %appdata% (Type that into the run
> > > > > > dialog)?
> > > > > > If so, delete it and try again.
> > > > > > 
> > > > > > Bill
> > > > > > 
> > > > > > > On Nov 8, 2015, at 16:52, novelistics notifications@github.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > Hi, texsting your product. I installed it and tried to authorize
> > > > > > > it.
> > > > > > > The
> > > > > > > twitter page came up with an error, and now the program won't run.
> > > > > > > It
> > > > > > > will
> > > > > > > sstill install, but not load the authorize dialogue box.
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > https://github.com/manuelcortez/TWBlue/issues/64.
> > > > > > 
> > > > > > ---
> > > > > > 
> > > > > > Reply to this email directly or view it on GitHub:
> > > > > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Pen Name:
> > > > > Mellissa Green
> > > > > Twitter
> > > > > @abluegreenunivs
> > > > > 
> > > > > website
> > > > > 
> > > > > www.abluegreenuniverse.com
> > > > 
> > > > ## 
> > > > 
> > > > Pen Name:
> > > > Mellissa Green
> > > > Twitter
> > > > @abluegreenunivs
> > > > 
> > > > website
> > > > 
> > > > www.abluegreenuniverse.com
> > > 
> > > ## 
> > > 
> > > Pen Name:
> > > Mellissa Green
> > > Twitter
> > > @abluegreenunivs
> > > 
> > > website
> > > 
> > > www.abluegreenuniverse.com
> > 
> > ## 
> > 
> > Pen Name:
> > Mellissa Green
> > Twitter
> > @abluegreenunivs
> > 
> > website
> > 
> > www.abluegreenuniverse.com
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154910593.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154911355

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by ghost** [comment]
I had to reset Twblue and looked at Twblue snapshot for a brief
moment. Will the tweet liking feature be in a future version of the
normal release of Twblue?

On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:

> It's very nice.
> 
> On 11/8/15, Bill Dengler notifications@github.com wrote:
> 
> > The client is for blind users.
> > I don’t know where the name originated from, I’m not the project
> > author/maintainer but have collaborated with him on it.
> > @manuelcortez @jmdaweb creo que podéis cerrar esto ahora.
> > 
> > > On Nov 8, 2015, at 22:38, novelistics notifications@github.com wrote:
> > > 
> > > I'm in. Love the name, where did it come from? Blue is my favorite
> > > color, check out my website, abluegreenuniverse.com
> > > 
> > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > wrote:
> > > 
> > > > Twitter error. Something is technically wrong.
> > > > 
> > > > Thanks for noticing—we're going to fix it up and have things back to
> > > > normal soon.
> > > > 
> > > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > > wrote:
> > > > 
> > > > > I've deleted the folder, now will try again.
> > > > > 
> > > > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > > > wrote:
> > > > > 
> > > > > > I'm not sure what the error was.
> > > > > > 
> > > > > > On 11/8/15, Bill Dengler notifications@github.com wrote:
> > > > > > 
> > > > > > > What was the error you got from the Twitter page?
> > > > > > > Is there a TWBlue folder in your %appdata% (Type that into the run
> > > > > > > dialog)?
> > > > > > > If so, delete it and try again.
> > > > > > > 
> > > > > > > Bill
> > > > > > > 
> > > > > > > > On Nov 8, 2015, at 16:52, novelistics notifications@github.com
> > > > > > > > wrote:
> > > > > > > > 
> > > > > > > > Hi, texsting your product. I installed it and tried to authorize
> > > > > > > > it.
> > > > > > > > The
> > > > > > > > twitter page came up with an error, and now the program won't run.
> > > > > > > > It
> > > > > > > > will
> > > > > > > > sstill install, but not load the authorize dialogue box.
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > https://github.com/manuelcortez/TWBlue/issues/64.
> > > > > > > 
> > > > > > > ---
> > > > > > > 
> > > > > > > Reply to this email directly or view it on GitHub:
> > > > > > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Pen Name:
> > > > > > Mellissa Green
> > > > > > Twitter
> > > > > > @abluegreenunivs
> > > > > > 
> > > > > > website
> > > > > > 
> > > > > > www.abluegreenuniverse.com
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Pen Name:
> > > > > Mellissa Green
> > > > > Twitter
> > > > > @abluegreenunivs
> > > > > 
> > > > > website
> > > > > 
> > > > > www.abluegreenuniverse.com
> > > > 
> > > > ## 
> > > > 
> > > > Pen Name:
> > > > Mellissa Green
> > > > Twitter
> > > > @abluegreenunivs
> > > > 
> > > > website
> > > > 
> > > > www.abluegreenuniverse.com
> > > 
> > > ## 
> > > 
> > > Pen Name:
> > > Mellissa Green
> > > Twitter
> > > @abluegreenunivs
> > > 
> > > website
> > > 
> > > www.abluegreenuniverse.com
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154910593.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154911355
> 
> ## 
> 
> Pen Name:
> Mellissa Green
> Twitter
> @abluegreenunivs
> 
> website
> 
> www.abluegreenuniverse.com

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by codeofdusk** [comment]
Maybe, but the standard release hasn’t been updated in ages. Manuel may or may not do it.
For the absolute latest changes, check out http://n6.io/magenta
I maintain that project.
Bill

**Comment by ghost** [comment]
What's the difference between Project Magenta and Twblue.

On 11/12/15, Bill Dengler notifications@github.com wrote:

> Maybe, but the standard release hasn’t been updated in ages. Manuel may or
> may not do it.
> For the absolute latest changes, check out http://n6.io/magenta
> I maintain that project.
> Bill
> 
> > On Nov 12, 2015, at 22:10, novelistics notifications@github.com wrote:
> > 
> > I had to reset Twblue and looked at Twblue snapshot for a brief
> > moment. Will the tweet liking feature be in a future version of the
> > normal release of Twblue?
> > 
> > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > wrote:
> > 
> > > It's very nice.
> > > 
> > > On 11/8/15, Bill Dengler notifications@github.com wrote:
> > > 
> > > > The client is for blind users.
> > > > I don’t know where the name originated from, I’m not the project
> > > > author/maintainer but have collaborated with him on it.
> > > > @manuelcortez @jmdaweb creo que podéis cerrar esto ahora.
> > > > 
> > > > > On Nov 8, 2015, at 22:38, novelistics notifications@github.com
> > > > > wrote:
> > > > > 
> > > > > I'm in. Love the name, where did it come from? Blue is my favorite
> > > > > color, check out my website, abluegreenuniverse.com
> > > > > 
> > > > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > > > wrote:
> > > > > 
> > > > > > Twitter error. Something is technically wrong.
> > > > > > 
> > > > > > Thanks for noticing—we're going to fix it up and have things back
> > > > > > to
> > > > > > normal soon.
> > > > > > 
> > > > > > On 11/8/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com
> > > > > > wrote:
> > > > > > 
> > > > > > > I've deleted the folder, now will try again.
> > > > > > > 
> > > > > > > On 11/8/15, Nicole Valicia Thompson-Andrews
> > > > > > > goldyemoran@gmail.com
> > > > > > > wrote:
> > > > > > > 
> > > > > > > > I'm not sure what the error was.
> > > > > > > > 
> > > > > > > > On 11/8/15, Bill Dengler notifications@github.com wrote:
> > > > > > > > 
> > > > > > > > > What was the error you got from the Twitter page?
> > > > > > > > > Is there a TWBlue folder in your %appdata% (Type that into the
> > > > > > > > > run
> > > > > > > > > dialog)?
> > > > > > > > > If so, delete it and try again.
> > > > > > > > > 
> > > > > > > > > Bill
> > > > > > > > > 
> > > > > > > > > > On Nov 8, 2015, at 16:52, novelistics
> > > > > > > > > > notifications@github.com
> > > > > > > > > > wrote:
> > > > > > > > > > 
> > > > > > > > > > Hi, texsting your product. I installed it and tried to
> > > > > > > > > > authorize
> > > > > > > > > > it.
> > > > > > > > > > The
> > > > > > > > > > twitter page came up with an error, and now the program won't
> > > > > > > > > > run.
> > > > > > > > > > It
> > > > > > > > > > will
> > > > > > > > > > sstill install, but not load the authorize dialogue box.
> > > > > > > > > > 
> > > > > > > > > > —
> > > > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > > > https://github.com/manuelcortez/TWBlue/issues/64.
> > > > > > > > > 
> > > > > > > > > ---
> > > > > > > > > 
> > > > > > > > > Reply to this email directly or view it on GitHub:
> > > > > > > > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154887580
> > > > > > > > 
> > > > > > > > ## 
> > > > > > > > 
> > > > > > > > Pen Name:
> > > > > > > > Mellissa Green
> > > > > > > > Twitter
> > > > > > > > @abluegreenunivs
> > > > > > > > 
> > > > > > > > website
> > > > > > > > 
> > > > > > > > www.abluegreenuniverse.com
> > > > > > > 
> > > > > > > ## 
> > > > > > > 
> > > > > > > Pen Name:
> > > > > > > Mellissa Green
> > > > > > > Twitter
> > > > > > > @abluegreenunivs
> > > > > > > 
> > > > > > > website
> > > > > > > 
> > > > > > > www.abluegreenuniverse.com
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Pen Name:
> > > > > > Mellissa Green
> > > > > > Twitter
> > > > > > @abluegreenunivs
> > > > > > 
> > > > > > website
> > > > > > 
> > > > > > www.abluegreenuniverse.com
> > > > > 
> > > > > ## 
> > > > > 
> > > > > Pen Name:
> > > > > Mellissa Green
> > > > > Twitter
> > > > > @abluegreenunivs
> > > > > 
> > > > > website
> > > > > 
> > > > > www.abluegreenuniverse.com
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154910593.
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-154911355
> > > 
> > > ## 
> > > 
> > > Pen Name:
> > > Mellissa Green
> > > Twitter
> > > @abluegreenunivs
> > > 
> > > website
> > > 
> > > www.abluegreenuniverse.com
> > 
> > ## 
> > 
> > Pen Name:
> > Mellissa Green
> > Twitter
> > @abluegreenunivs
> > 
> > website
> > 
> > www.abluegreenuniverse.com
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-156310447.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-156310618

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by codeofdusk** [comment]
Very little. Project Magenta is a mirror, for the most part, of TWBlue, but some unofficial changes by me go to Magenta before TWBlue accepts them.
But I haven’t been maintaining it very much lately.
Bill

**Comment by SMORTIZ** [comment]
Hi, i have an issue. Lately the software is not working in mi computer, for some unknow reason is not launching the start. I uninstalled the software and reinstalled but still not working.  Could you please help me?

**Comment by jmdaweb** [comment]
Hello.
If you have updated to the latest snapshot, you must remove your config folder and authorise your accounts. Goto %appdata% and delete the TWBlue folder.
Regards,
Jose Manuel Delicado

**Comment by SMORTIZ** [comment]
Manuel, veo que hablas español. Busqué la carpeta que me has mencionado, sin embargo no la he encontrado. Cabe aclarar que yo instalé la versi{on completa no la Snapshot. Y corría muy bien el programa pero desafortunadamente ha dejado de funcionar, yo utilizo el windows 10, tendrá algo que ver, ya he reinstalado varias veces el programa pero sigue sin funcionar.¿ Alguna sugerencia?

**Comment by jmdaweb** [comment]
Vaya, gracias por cambiar el idioma, ¡mucho mejor así! Si tienes la versión estable, me temo que ya no funciona en Windows 10, al menos en el modo invisible. Te recomiendo que utilices la snapshot, a estas alturas tiene incluso más fallos corregidos que la estable, y muchas características nuevas.
Un saludo.

**Comment by manuelcortez** [comment]
Guys, this is not a support page, so I will close this bug (because I can't see any unreported bug here), for more questions or support, mention to @tw_blue2, @manuelcortez00 or @jmdaweb.

**Comment by ghost** [comment]
I fixed it. When is the update of Twblue coming out?

On 11/23/15, Manuel Cortéz notifications@github.com wrote:

> Guys, this is not a support page, so I will close this bug (because I can't
> see any unreported bug here), for more questions or support, mention to
> @tw_blue2, @manuelcortez00 or @jmdaweb.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-158962286

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by ghost** [comment]
My tokin has disappeared.

On 11/23/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:

> I fixed it. When is the update of Twblue coming out?
> 
> On 11/23/15, Manuel Cortéz notifications@github.com wrote:
> 
> > Guys, this is not a support page, so I will close this bug (because I
> > can't
> > see any unreported bug here), for more questions or support, mention to
> > @tw_blue2, @manuelcortez00 or @jmdaweb.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-158962286
> 
> ## 
> 
> Pen Name:
> Mellissa Green
> Twitter
> @abluegreenunivs
> 
> website
> 
> www.abluegreenuniverse.com

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by ghost** [comment]
It says that my token is inactive of the authorization failed.

On 11/28/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:

> My tokin has disappeared.
> 
> On 11/23/15, Nicole Valicia Thompson-Andrews goldyemoran@gmail.com wrote:
> 
> > I fixed it. When is the update of Twblue coming out?
> > 
> > On 11/23/15, Manuel Cortéz notifications@github.com wrote:
> > 
> > > Guys, this is not a support page, so I will close this bug (because I
> > > can't
> > > see any unreported bug here), for more questions or support, mention to
> > > @tw_blue2, @manuelcortez00 or @jmdaweb.
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/manuelcortez/TWBlue/issues/64#issuecomment-158962286
> > 
> > ## 
> > 
> > Pen Name:
> > Mellissa Green
> > Twitter
> > @abluegreenunivs
> > 
> > website
> > 
> > www.abluegreenuniverse.com
> 
> ## 
> 
> Pen Name:
> Mellissa Green
> Twitter
> @abluegreenunivs
> 
> website
> 
> www.abluegreenuniverse.com

## 

Pen Name:
Mellissa Green
Twitter
@abluegreenunivs

website

www.abluegreenuniverse.com

**Comment by codeofdusk** [comment]
Not general support box.
@manuelcortez please close this issue.

Bill
