### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by ghost** [manuelcortez/TWBlue#65]
Hi, my token needs to be reset. I just re-installed the program and because I couldn't log in. I still can't log in.

**Comment by manuelcortez** [comment]
Sorry, again, but this is not a support page. This page is for reporting  bugs in the development of this software. If you want your questions to be answered, you have to ask these in the right place. And this is not the right place. Follow @tw_blue2 account to read why you can't authorise your client. Short answer: download TWBlue again.
