### ISSUE TITLE
Trouble uploading photos

### ISSUE THREAD

**Issue by athena223** [manuelcortez/TWBlue#77]
When I try to upload a photo I get a message that says the connection to the machine has been refused. This prevents me from uploading photos.

**Comment by manuelcortez** [comment]
Are you running TWBlue from sources? It should be fixed already.

**Comment by manuelcortez** [comment]
As it seems this has been fixed in [This commit](https://github.com/manuelcortez/TWBlue/commit/c4e2c3b57a03c3b1c4d56d102414aad8dd98ac8f) I'm going to close this issue. If there are more problems, we'll re-open it.
