### ISSUE TITLE
Loading more tweets

### ISSUE THREAD

**Issue by jonasmarques** [manuelcortez/TWBlue#81]
When a specific user timeline is opened, the tweets who TW Blue is capable to load is limited. 
So, is'nt possible to load more  tweets when this limit is reached.

**Comment by manuelcortez** [comment]
Unfortunately this isn't in our control, according to [this page](https://dev.twitter.com/rest/reference/get/statuses/user_timeline) in the Twitter API:

> This method can only return up to 3,200 of a user’s most recent Tweets.
