### ISSUE TITLE
Nothing is happening when I start twblue

### ISSUE THREAD

**Issue by burakyuksek** [manuelcortez/TWBlue#82]
Hello,
For several weeks now I cannot do anything with the TWBlue client. When I start it up it just closes without saying anything. I am not the only one having this issue. Can you please clerify what's going on? Thank you.

**Comment by OzancanKaratas** [comment]
Merhaba Burak Bey,
Sizden öğrenmem gereken birkaç şey var. Lütfen <a href=mailto:"ozancankaratas96@outlook.com">buradan bana e-posta göndererek</a> ya da <a href=tel:"+905533919292">0 (553) 391 92 92</a> numaralı telefonu arayarak bana ulaşabilir misiniz? @burakyuksek

**Comment by manuelcortez** [comment]
Delete the config file. If something has happened with a session, TWBlue will not be able to load anything.  I have fixed this problem in a recent commit, but for now you will have to remove the config directory, this could be in the TWBlue directory (if you're using portable) or in %appdata%/twblue in installed. Then, restart TWBlue and configure your account again.

**Comment by burakyuksek** [comment]
Alright, I have solved the issue. Thank you.

04.07.2016 17:35 tarihinde Manuel Cortéz yazdı:
